### ISSUE TITLE
Issue (dll numpy) Python 3.6 on windows

### ISSUE THREAD

**Issue by bouhlelma** [SMTorg/smt#113]
![screenshot from 2018-09-26 13-30-02](https://user-images.githubusercontent.com/18660175/46097864-fa160a80-c190-11e8-9f2c-0185289526c4.png)

**Comment by relf** [comment]
I found the following related issues on numpy repo: [numpy #9272](https://github.com/numpy/numpy/issues/10714).

**Comment by relf** [comment]
Just to mention here that even if there is a problem with Windows Appveyor numpy installation, the SMT tests pass on my Windows 7 PC with Python 3.6 without any problem.

**Comment by relf** [comment]
PR #114 fixes this issue.
