### ISSUE TITLE
Torsion_vibration and water_flow are monotone in every coordinate

### ISSUE THREAD

**Issue by denis-bz** [SMTorg/smt#116]
Just a comment, not an issue:
the test cases torsion_vibration (15d) and water_flow (8d) both seem to be monotone,
increasing or decreasing, in every coordinate, so the optima are on the bounding boxes;
see `Coord-sketch.py` and .log under https://gist.github.com/denis-bz .
Does anyone know of more realistic test cases ?

**Comment by bouhlelma** [comment]
You can find several types of test functions here:
https://www.sfu.ca/~ssurjano/rosen.html
