### ISSUE TITLE
Citation format

### ISSUE THREAD

**Issue by tianyikillua** [SMTorg/smt#118]
I'm using your kriging implemention and LHS method to construct a surrogate model of injection molding simulations (similar to this [one](https://hal.archives-ouvertes.fr/hal-01683052)). Are you ok with this citation format

```
M. A. Bouhlel, et al., Surrogate modeling toolbox, 2018. URL:https://github.com/SMTorg/SMT.
```

or do I need to add more information? Thanks!

**Comment by bouhlelma** [comment]
Hi,
I suggest you to just add the URL in the footnote.
We have a paper on SMT which is under review right now, I will let you know if there is an update.

**Comment by relf** [comment]
Citation information is available [here](http://mdolab.engin.umich.edu/content/python-surrogate-modeling-framework-derivatives)
BibTeX format:
<pre>
@article {1327,
	title = {A Python surrogate modeling framework with derivatives},
	journal = {Advance in Engineering Software},
	year = {2019},
	author = {Mohamed Amine Bouhlel and John T. Hwang and Nathalie Bartoli and R{\'e}mi Lafage and Joseph Morlier and Joaquim R. R. A. Martins}
}
</pre>
