### ISSUE TITLE
Help me emstimate surrogates model

### ISSUE THREAD

**Issue by nguyenhoaiThanhbk2811** [SMTorg/smt#128]
Dear you.
Now I have the three input parameters. The each parameter I have the 20 values look like that.

nodes1 = np.array([0.05675, 0.05934, 0.05633, 0.0557 , 0.05702, 0.06401, 0.06322, 0.06571, 0.06099, 0.05832, 0.06196, 0.06463, 0.05507, 0.06351, 0.06287, 0.06122, 0.05407, 0.05985, 0.05774,0.06015])

nodes2 = np.array([0.9486, 0.9095, 0.9856, 0.9318, 1.0477, 1.0489,1.0663, 0.9184, 0.9646, 1.0345, 1.0168, 1.0565, 0.9727, 0.9907, 0.9277, 0.9548, 1.0933, 1.0751,1.0026, 1.0231])

nodes3 = np.array([51.813, 54.279, 52.659, 51.197 , 46.629, 49.791, 48.581, 54.799, 46.413, 47.078, 52.367, 48.204, 50.389, 45.402, 47.893, 50.796 , 49.332, 53.323, 53.713, 45.757])

each pair of value I have a output : example: (node1_1; node2_1; node3_1) have a output ( 0.0204232), so I have the 20 output values.

output=np.array([0.0204232,0.0205054,0.0204971,0.0204463,0.0206686,0.0206678,0.0206883,0.0204627,0.020426,0.0206532,0.0206322,0.020677,0.0204431,0.0205319,0.0204508,0.0204115,0.020721,0.0206988,0.0206179,0.0206418])

how to apply the kriging method find the surrogates model for input and output?
please help me. thanks you so much

**Comment by bouhlelma** [comment]
Hi,
You have a Kriging example here: https://smt.readthedocs.io/en/latest/_src_docs/surrogate_models/krg.html
