### ISSUE TITLE
RMTB does not build properly on OSX >= 10.13

### ISSUE THREAD

**Issue by JustinSGray** [SMTorg/smt#130]

**Comment by JustinSGray** [comment]
this is the error i get: 
```  File "/Users/jsgray/anaconda3/envs/py3.6/lib/python3.6/site-packages/smt/surrogate_models/rmtb.py", line 18, in <module>
    from smt.surrogate_models.rmtsclib import PyRMTB
ImportError: dlopen(/Users/jsgray/anaconda3/envs/py3.6/lib/python3.6/site-packages/smt/surrogate_models/rmtsclib.cpython-36m-darwin.so, 2): Symbol not found: __ZTINSt8ios_base7failureB5cxx11E
  Referenced from: /Users/jsgray/anaconda3/envs/py3.6/lib/python3.6/site-packages/smt/surrogate_models/rmtsclib.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/jsgray/anaconda3/envs/py3.6/lib/python3.6/site-packages/smt/surrogate_models/rmtsclib.cpython-36m-darwin.so```

**Comment by JustinSGray** [comment]
I was able to get it to build correctly by setting the compilers to g++ explicitely. neither apple's built in clang or gcc worked for me.

**Comment by cyrilpic** [comment]
I could have it compile with gcc and clang by setting the deployment target in setup.py (rather at the top).

```python
if sys.platform == 'darwin':
    os.environ['MACOSX_DEPLOYMENT_TARGET'] = '10.9'
```

**Comment by relf** [comment]
Thank you for reporting. No way for me to test that directly. I've just upgraded the travis macos config to test with 10.13 and it seems ok.

**Comment by m-meliani** [comment]
I had a similar problem installing smt on MacOS 10.14: c++ compiler not finding stdlibc++ 
![image](https://user-images.githubusercontent.com/18448391/53895460-61829100-4032-11e9-932b-1b71315da329.png)

I found this explanation in a pandas GitHub issue: https://github.com/pandas-dev/pandas/issues/23424
> The compiler standard library defaults to either libstdc++ or libc++, depending on the targetted macOS version - libstdc++ for 10.8 and below, and libc++ for 10.9 and above. This is determined by the environment variable MACOSX_DEPLOYMENT_TARGET or the compiler option-mmacosx-version-min, defaulting to the system version otherwise.

@cyrilpic workaround seems to have fixed it
