### ISSUE TITLE
Avoid printing training details

### ISSUE THREAD

**Issue by ArioBattolla** [SMTorg/smt#144]
Hi!
Is there a way to avoid printing all the details for training the surrogate models? Like a verbose=False. 
Thank you very much.

**Comment by relf** [comment]
Hi! Could you give more information? Which surrogate do you use and how? Could you show the printing?

**Comment by ArioBattolla** [comment]
I am using for example RBF surrogate. 
When I use the method sm.train() or sm.predict_values() it automatically print on the IPython console all the details of the training (I am using spyder).

Example:
  RBF
___________________________________________________________________________
   
 Problem size
   
      # training points.        : 20
   
___________________________________________________________________________
   
 Training
   
   Training ...
      Initializing linear solver ...
         Performing LU fact. (20 x 20 mtx) ...
         Performing LU fact. (20 x 20 mtx) - done. Time (sec):  0.0000000
      Initializing linear solver - done. Time (sec):  0.0000000
      Solving linear system (col. 0) ...
         Back solving (20 x 20 mtx) ...
         Back solving (20 x 20 mtx) - done. Time (sec):  0.0010002
      Solving linear system (col. 0) - done. Time (sec):  0.0010002
   Training - done. Time (sec):  0.0030003
___________________________________________________________________________
   
 Evaluation
   
      # eval points. : 100
   
   Predicting ...
   Predicting - done. Time (sec):  0.0000000
   
   Prediction time/pt. (sec) :  0.0000000

**Comment by relf** [comment]
add the following: <code>rbf.options['print_global'] = False</code> where rbf is the surrogate object.

See RBF surrogate options [here](https://smt.readthedocs.io/en/latest/_src_docs/surrogate_models/rbf.html)

**Comment by ArioBattolla** [comment]
Ah I see now, thank you very much!!
