### ISSUE TITLE
How to compute gradients?

### ISSUE THREAD

**Issue by ArioBattolla** [SMTorg/smt#147]
Hi, 
I have read your documentation and gradient-enhanced KPLS models seem really promising. However I did not see any function in your documentation that enables to compute training derivatives to feed into the model.
In a general problem, how can I do that? Using finite differencing? Do you have any external code, source that you can suggest me to compute gradients?
Thank you very much.

**Comment by relf** [comment]
You do not see anything related to derivatives computation themselves as it is not in the scope of SMT.
Regarding derivatives computation it depends on which level of control you have on the numerical model you want to differentiate. Indeed if it is a black box you are good to go with finite-differentiation.

You can find a review of derivatives computation methods in this [paper](http://mdolab.engin.umich.edu/content/review-and-unification-discrete-methods-computing-derivatives-single-and-multi-disciplinary). Regarding tools supporting derivative computations, I use [OpenMDAO  ](https://openmdao.org/).
