### ISSUE TITLE
Multiple input features cannot have the same value

### ISSUE THREAD

**Issue by ArioBattolla** [SMTorg/smt#148]
Hi, 

I am trying to implement a KPLS model with my dataset, but it raises this error:
"Multiple input features cannot have the same value".

How can I solve it?

Thank you very much for your support

EDIT: I solved by dropping equal instances, by using dataframe.drop_duplicates()
However now, it seems it is not converging and gives me thousands of these exceptions:

....
exception :  125-th leading minor of the array is not positive definite
exception :  125-th leading minor of the array is not positive definite
exception :  136-th leading minor of the array is not positive definite
exception :  array must not contain infs or NaNs
exception :  array must not contain infs or NaNs
exception :  array must not contain infs or NaNs
.....

How can I solve this problem? 
Thank you very much :)

**Comment by bouhlelma** [comment]
This error indicates that you have two identical samples in your dataset. You need to remove all duplicate samples from your dataset before using KPLS.

**Comment by ArioBattolla** [comment]
Yes,I had already solved that problem. In the EDIT part, I wrote the new issue that I am facing. I re-write it here:
EDIT: I solved by dropping equal instances, by using dataframe.drop_duplicates()
However now, it seems it is not converging and gives me thousands of these exceptions:

....
exception : 125-th leading minor of the array is not positive definite
exception : 125-th leading minor of the array is not positive definite
exception : 136-th leading minor of the array is not positive definite
exception : array must not contain infs or NaNs
exception : array must not contain infs or NaNs
exception : array must not contain infs or NaNs
.....

How can I solve this problem?
Thank you very much :)

**Comment by relf** [comment]
We need more information. Could you give a stack trace, information about your training data and a code sample?

**Comment by ArioBattolla** [comment]
I am trying to use KPLS, with a search algorithm to find the value of theta that gives the best result.
This is the code:

```

# Define kFold for cross validation
seed=1
from sklearn.model_selection import KFold
n_splits = min(int(np.sqrt(X0_train.shape[0])), 10)
print("n splits:", n_splits)
kfold = KFold(n_splits=n_splits, shuffle=True, random_state=1)

# Kriging
teta_search = np.linspace(0.1,2,10) #values of theta to try
best_scores_sm = 0
best_param = 0
score_mean = -math.inf


for teta in teta_search:
    scores = []
    for train_index, test_index in kfold.split(X0_train):
        X_train, X_test = X0_train[train_index], X0_train[test_index]
        y_train, y_test = y0_train[train_index], y0_train[test_index]
        
        sm = KPLS(theta0=[teta], n_comp=1, print_global=False)
        sm.set_training_values(X_train, y_train)
        sm.train()

        y_pred_test = sm.predict_values(X_test)
        scores.append(r2_score(y_pred_test, y_test))
    print(np.mean(scores))
    if (np.mean(scores) < score_mean):
        continue;
    else:
        score_mean = np.mean(scores)
        best_scores_sm = scores
        best_param = teta
print("d0", best_param)
print("best_score", np.mean(best_scores_sm),"+/-", np.std(best_scores_sm))

```


The problem appears when I want to try low values of theta, for example theta=[0.01]. And the problem appears using "sm.train()". For higher values of theta it works but the results aren't so good.

**Comment by ArioBattolla** [comment]
I found that the errors come from here:

```
        try:
            C = linalg.cholesky(R, lower=True)
        except (linalg.LinAlgError, ValueError) as e:
            print("exception : ", e)
            return reduced_likelihood_function_value, par
```

This can be found in krg_based.py
If I try low values of theta, it starts giving an infinite series of exception. 
How can I solve that problem?

**Comment by relf** [comment]
Numerical issue related to the positive semidefinite quality of the covariance matrix: see [some hints ](https://github.com/iancze/Starfish/issues/26#issuecomment-479112856) to tackle the problem.
