### ISSUE TITLE
I am not able To extract the variances of new points

### ISSUE THREAD

**Issue by dobhalnitish** [SMTorg/smt#152]
I am not able To extract the variances of new points.
Here is my code
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D 
from smt.surrogate_models import RBF
sm = RBF(print_training=False)
sm.options['print_prediction'] = False

def black(x,y):
    return (1-x)**2+(y-x)**2

# Intialising with some data
xt = np.random.randn(100,2)*10
z=[]
for i in range(100):
    temp=(black(xt[i][0],xt[i][1]))
    z.append(temp)
Z=(np.array(z))
sm = RBF(d0=5)
sm.set_training_values(xt,Z)
sm.train()

# Done Modeling Now we will start plotting
fig = plt.figure()
ax = Axes3D(fig)
surf = ax.plot_trisurf(xt[:,0], xt[:,1], Z, cmap=cm.jet, linewidth=0.1)
fig.colorbar(surf, shrink=0.5, aspect=5)
ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Joining Points')
#plt.savefig('teste.pdf')
plt.show()

# Now we will plot the actual curve

# MOdeling Function
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
yt = np.linspace(-10,10,50)
xt = np.linspace(-10,10,50)
X, Y = np.meshgrid(xt, yt)
final=[]
for i in range(len(xt)):
    for j in range(len(xt)):
        final.append([xt[i],yt[j]])
zs  = sm.predict_values(np.array(final))
var = sm.predict_variances()
Z=np.zeros((50,50))
for i in range(len(final)):
    Z[i//50][i%50]=zs[i]
ax.plot_surface(X, Y, Z)
ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Modeling')
plt.show()

# The Error it is showing :
NotImplementedError                       Traceback (most recent call last)
<ipython-input-225-50884bd4c492> in <module>
     11         final.append([xt[i],yt[j]])
     12 zs  = sm.predict_values(np.array(final))
---> 13 var = sm.predict_variances(xt)
     14 Z=np.zeros((50,50))
     15 for i in range(len(final)):

~\Anaconda3\lib\site-packages\smt\surrogate_models\surrogate_model.py in predict_variances(self, x)
    333             Variances.
    334         """
--> 335         check_support(self, 'variances')
    336         check_nx(self.nx, x)
    337         n = x.shape[0]

~\Anaconda3\lib\site-packages\smt\utils\checks.py in check_support(sm, name, fail)
     21     if not sm.supports[name] or fail:
     22         class_name = sm.__class__.__name__
---> 23         raise NotImplementedError('{} does not support {}'.format(class_name, name))
     24 
     25 def check_nx(nx, x):

NotImplementedError: RBF does not support variances

**Comment by relf** [comment]
As stated by the last line, RBF surrogate does not support variance computation. If you want variance information you have to use a surrogate from the Kriging family. 

Indeed, this is not explicitly mentioned in the documentation. You get the feature support information either by a raised exception (like you did) or by browsing the <code>_initialize</code> method code of the given surrogate and seeking for a <code>support["variances"] = True</code> line (like [here](https://github.com/SMTorg/smt/blob/4feae514bded0733d438a6cd50ffbabb84be4b90/smt/surrogate_models/krg_based.py#L64)).

**Comment by dobhalnitish** [comment]
Thanks a Lot. :D
