### ISSUE TITLE
Kriging based surrogates are not pickable

### ISSUE THREAD

**Issue by relf** [SMTorg/smt#153]
Current Kriging based surrogates are not pickable because of options related to regression or correlation functions which are actual functions which results in the following error message
<pre>
cPickle.PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
</pre>
Actually the declaration of those options (<code>poly</code>, <code>corr</code>)  is a bit hacky as such option allows to specify a callable while acceptable values are documented to be an enumerate.
This implementation has the benefit to allow the user to specify is own functions for correlation and regression but it prevents from pickling. 
I would like to propose a pull request to modify the code to have the current Krigings implementation pickable (hence make these options an enumerate). I am not sure at the moment on what is the best way to keep the "user-defined correlation or regression functions" capability. Is it used? Do we have to keep it? Plugin mechanism? Any thoughts?

**Comment by bouhlelma** [comment]
user-defined correlation or regression functions is not supported by SMT. In the current version of SMT, if the user wants to add a defined function, he has to declare it manually. I agree to make these options an enumerate

**Comment by relf** [comment]
My point is that currently the user could declare his own function and give it to the <code>corr</code> or <code>poly</code> options which are of FunctionType type (and provided the user knows what he is doing). By using an enumerate, we will loose this capability. 
But if you are ok, it is fine with me. If really need be, we could add new functions in <code>kriging_utils</code> or think about a plugin mechanism to allow the user defined functions later on.
