### ISSUE TITLE
How to control verbosity?

### ISSUE THREAD

**Issue by dobhalnitish** [SMTorg/smt#157]
I My query is , is there any provision provided in the library to not print the intermediate info.
If yes? Can you please tell me.
If no, Can you suggest me where should I change in the code.

**Comment by relf** [comment]
Yes. All surrogates have an option for that:
<pre>
surrogate.options['print_global'] = False
</pre>
You can also find this information in the documentation. 
Please for further issues, try to give a more significant title like "How to control verbosity?", thanks.
