### ISSUE TITLE
Kriging variance prediction not working for multiple points

### ISSUE THREAD

**Issue by jbussemaker** [SMTorg/smt#160]
I'm trying to predict the variance of a Kriging-based surrogate model for multiple points at a time, but it seems that the function is only implemented for one point at a time.

Reproduce using (note that pull requests #158 and #159 first need to be accepted):
```python
# Python 3.6
# SMT 0.3.3
import numpy as np
from smt.surrogate_models.krg import KRG

x = np.random.random((10, 3))
y = np.random.random((10, 2))

kriging = KRG(theta0=[1e-2]*3)
kriging.set_training_values(x, y)
kriging.train()

var = kriging.predict_variances(x)
```

This results in:
```
Traceback (most recent call last):
  File "reproduce.py", line 11, in <module>
    var = kriging.predict_variances(x)
  File "....\site-packages\smt\surrogate_models\surrogate_model.py", line 370, in predict_variances
    s2 = self._predict_variances(x)
  File "....\site-packages\smt\surrogate_models\krg_based.py", line 389, in _predict_variances
    1.0 - (rt ** 2.0).sum(axis=0) + (u ** 2.0).sum(axis=0)
ValueError: operands could not be broadcast together with shapes (2,) (10,) 
```

Replacing the last line with the following makes the prediction work:
```python
var = np.zeros(y.shape)
for i in range(x.shape[0]):
    var[i, :] = kriging.predict_variances(x[[i], :])
```

It would be nice if this could be corrected.

**Comment by relf** [comment]
Indeed there is an issue. Actually it works when the output y is one-dimensional. Kriging <code>predict_variance</code> really lacks of testing but moreover it happens that our tests or problems have all one-dimensional output, which is really bad (more bugs may be lurking). Thanks for reporting.

**Comment by bouhlelma** [comment]
Thanks to @relf, this issue should be fixed now.
