### ISSUE TITLE
Optimization framework+adding CNN surrogate base model

### ISSUE THREAD

**Issue by aimanian** [SMTorg/smt#165]
Hello,

I would appreciate if you can let me know about any open source optimization code, that can use your surrogate model outputs for optimization process. 
In addition, I would like to know if that is possible to add convectional neural network (CNN) to your already developed surrogate models.

Thanks,
Anahita

**Comment by relf** [comment]
As far as I am concerned, I am not aware of an open source optimizer using SMT. But we think about adding an [EGO](https://link.springer.com/article/10.1023/A:1008306431147) implementation as an extension in the coming months.
We are open to any contribution provided it matches the scope of SMT (see [Developer section in the documentation](https://smt.readthedocs.io/en/latest/_src_docs/dev_docs.html)). Thank you for your interest!

**Comment by aimanian** [comment]
Thanks for your reply!
Do you have also plan to add CNN to your surrogate models?

Thanks,
Anahita

**Comment by relf** [comment]
Well... No plan for CNN surrogate addition on my side. As a related topic, we've added the GENN surrogate model thanks to PR #123

**Comment by aimanian** [comment]
Thanks!
