### ISSUE TITLE
Problem running CRM wing case 

### ISSUE THREAD

**Issue by hknarahari** [SMTorg/smt#169]
I have been exploring the use of SMT package as a part of student curriculum here in our university, hence I have downloaded the package from github. I have tried out some of the examples without any issue but have run into a specific problem related to RMTB and RMTC methods. Either in the One_D_step or CRM_wing case I am getting a module not found error (screen shot attached). Any pointers to identify the error would be of great help. 
![SMT_CRM_Error](https://user-images.githubusercontent.com/54882722/65011744-4920f680-d932-11e9-8a59-f22525f06b8f.png)

**Comment by relf** [comment]
It looks like there is an installation problem. How did you install SMT?

**Comment by hknarahari** [comment]
I downloaded the files and using Anaconda environment used pip install. If there anotherway PL let me know, I will un-install and re-install. However, some of the other cases worked .

**Comment by relf** [comment]
If you have installed following the Readme here (<code>pip install -e smt_dir</code>) RMTB and RMTC are compiled on your machine during installation. Maybe something went wrong.

You can uninstall and then try to install from pypi directly with <code>pip install smt</code>.

**Comment by hknarahari** [comment]
If C or C++ compilers are need , then that may be the problem as my laptop
does not have it. Can I use other methods till I get the compilers ?

**Comment by relf** [comment]
That was exactly what I suggested. As you use Windows you can get binary distribution with:
<code>pip install smt</code>
Downloading the code followed by <code>pip install -e <smt folder></code> is for development mode i.e. when you want to develop within SMT library. If you just want to use SMT, direct install from Pypi with <code>pip install smt</code> is simpler (and do not require compilation on Windows).

**Comment by relf** [comment]
See also documentation [here](https://smt.readthedocs.io/en/latest/_src_docs/getting_started.html)

**Comment by hknarahari** [comment]
Hi,
Did as instructed (uninstalled and installed again) and ran 'testflo'. While some tests ran  OK some did not go through. As before I tried running CRM wing example and got a different error. I am attaching the testflo report as well as the screen shot of error message.

![smt_rmtb_error](https://user-images.githubusercontent.com/54882722/65414849-21d69780-de12-11e9-9bc7-e53f92b3cdeb.png)
[testflo_report.txt](https://github.com/SMTorg/smt/files/3641457/testflo_report.txt)
Thanks for looking into my issues,
Narahari

**Comment by relf** [comment]
First, two remarks:
* Installation with <code>pip install smt</code> will work without compilation only with Python 3, but I noticed you are still using Python 2.7. In that case, it may work with a previous version of smt: <code>pip install smt==0.2.2</code>
* I noticed you have an smt-master directory like you downloaded a zip then install from the zip file which will fail to compile RMTB or RMTC surrogates if you do not have the right C++ compiler. 

So, please just try: <code>pip install smt==0.2.2</code>
If it installs smt 0.2.2 successfully then you can use the code from the smt zip file you downloaded to run the crm wing example.
<code>python examples\rans_crm_wing\run_rans_crm_wing_rmtb.py</code>
do not execute from smt-master\smt directory, it might mess with the smt code present in the directory and smt code installed on your system.

**Comment by hknarahari** [comment]
Tried that but got this message 
![new_smt_error](https://user-images.githubusercontent.com/54882722/65441809-ac39ee00-de48-11e9-974c-47ecb5c94434.png)

**Comment by hknarahari** [comment]
I was using Python 3.6 but had to change to 2.7 as a couple of other packages run only on that. Can I have both versions of python (on different drives) working in the same laptop ? if so I may do that

**Comment by relf** [comment]
You can have several installation of Python. Then you just have to manage your paths consistently. The easier way to do that is to use Anaconda distribution with environments.

**Comment by relf** [comment]
I realize that what I suggest depends on the hardware architecture as well and will only work with a windows amd_64 (which is the architecture of my machine with which I generate SMT binaries).
Otherwise you have to compile SMT successfully. Again for that, I would suggest to install Anaconda distribution.

**Comment by hknarahari** [comment]
I have installed Anaconda with python 3.73 (have another environment for 2.7) , installed SMT using 'pip install smt' . Whn I run some of the cases in the tutorial (LS, QP, Krigging) it runs fine , but stops when I run the RMTB case. I am attaching the sc
![latest_SMT_error](https://user-images.githubusercontent.com/54882722/65818458-25fa1f00-e22f-11e9-9741-b4b1dc172cf6.png)
ree shot , as you can see .pyc files are there  , but the error I get is 'smt.examples' module not found.

**Comment by relf** [comment]
Examples are not meant to be installed  (the smt.examples package is not found hence the error). It works when installing in development mode <code>pip install -e smt_folder</code> because the code is in the smt_folder. 

If you want to make it work, copy <code>rans_crm_wing.py</code> and <code>run_rans_crm_wing_rmtb.py</code> in a directory, go in that directory, replace <code>from smt.examples.rans_crm_wing.rans_crm_wing ... </code> by <code>from rans_crm_wing ... </code> then just execute <code>python run_rans_crm_wing_rmtb.py</code>

**Comment by hknarahari** [comment]
That is it ! working now. I guess I need to do the same for all the other cases in 'examples' directory. Btw, there are plot commands in the file but I did not see any plots, shoild I remove the 'agg' option in the Mathplotlib?

**Comment by relf** [comment]
Indeed, comment out the <code>matplotlib.use("Agg")</code> line and you should see the plots.

**Comment by hknarahari** [comment]
Hey,

I just signed the petition "@MoHFW_INDIA @drharshvardhan : Make COVID-19
Testing Free for Senior Citizens & Subsidised for All
#PatientsBeforeProfits" and wanted to see if you could help by adding your
name.

Our goal is to reach 25,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/TxvhDRNBB9

Thanks!
Narahari
