### ISSUE TITLE
i'm trying to run RBF example

### ISSUE THREAD

**Issue by KKDDD** [SMTorg/smt#171]
RBF example has some errors
but other example is ok
![1569315489(1)](https://user-images.githubusercontent.com/21326738/65497390-c0372b80-deec-11e9-9eb6-663ba64ca657.png)
![1569315556(1)](https://user-images.githubusercontent.com/21326738/65497391-c0cfc200-deec-11e9-8ea3-f62e24cb3337.jpg)

**Comment by relf** [comment]
RBF like IDW, RMTB and RMTC have to be compiled (cython extensions). What is your Python, OS and hardware architecture? How did you install SMT? Did you get any error message during installation? see #169

**Comment by KKDDD** [comment]
![image](https://user-images.githubusercontent.com/21326738/66740483-eb86b800-eea5-11e9-866d-525c475a76e6.png)
it 's the error

**Comment by relf** [comment]
Please could you show the command? Would you mind answering previous questions? It is very difficult to help you with so few information.

**Comment by KKDDD** [comment]
I have install cython extensions,but RBF still doesn't work.(can not  import name RBF,IDW have the sam situation)
I find error came from rbf.py
![image](https://user-images.githubusercontent.com/21326738/66793635-e28ef880-ef30-11e9-99f8-6ef3ea6a1cc2.png)
rbfclib doesn't exist.

**Comment by KKDDD** [comment]
Tanks, i reinstall SMT,and RBF is work.
now,i want to konw what's the mean of parameter in the follow image
![image](https://user-images.githubusercontent.com/21326738/66798302-1d4c5d00-ef40-11e9-8317-ec28bdb205f1.png)
beacuse i find set the different value ,the prediction's graphics  is obviously different

**Comment by relf** [comment]
Please [read the docs](https://smt.readthedocs.io/en/latest/_src_docs/surrogate_models.html). You'll find information about surrogate options.
