### ISSUE TITLE
How to use SMT for discrete data

### ISSUE THREAD

**Issue by hknarahari** [SMTorg/smt#172]
Not an issue but was wondering how to use the toolbox when there is no function but a table of data ? For example if I  run Computational Fluid Dynamics code for a standard  case (generic  wing)  at a (1) set of angle of attack , (2) Mach Numbers, (3) Sweep angles and get Lift/Drag ratio. I am interested in  constructing a surrogate for the data in order to find optimal combination of angle of attack, sweep angle and Mach number. Of course,  the problem itself is old many people have worked on it, but I am interested in the process . How should I start ?
Thanks in advance

**Comment by bouhlelma** [comment]
Hello,
There is the b777_engine example at smt/examples/b777_engine/b777_engine.py where we use a table of data instead of a function.
