### ISSUE TITLE
Error using rmtb 

### ISSUE THREAD

**Issue by hknarahari** [SMTorg/smt#173]
I have run the tutorial case for CRM successfully (based on inputs given in the forum)  and am now trying on some synthetic data . I have a sample set of data values and have tried to use rmtb ( using tutorial script for CRM wing). It looks to be working fine except for the error in the last step. I am attaching the codes I have used and the screen shot of error.  Any suggestion would be of great help.
Thanks
Narahari

![shivu_error](https://user-images.githubusercontent.com/54882722/67090961-fc4a6d00-f1c8-11e9-8c33-676babe1d088.png)

**Comment by relf** [comment]
You've just put your data in the CRM wing example but your output is one-dimensional (dc60) while the example uses a two-dimensional output (CD, CL). You have to adapt the code too (at the very least suppress any CL related code).
