### ISSUE TITLE
High-dimension training problem

### ISSUE THREAD

**Issue by KKDDD** [SMTorg/smt#176]
i have train a 30-dimension surrogate by 1000 pionts,but the different input value have the same value.
if the dismension is 2,SMT does work well .
is that mean SMT don't support high-dimension?

**Comment by relf** [comment]
You mean **output** have the same value? Which surrogate did you choose? Regarding dimension, surrogates have various performance. For high dimension, I would recommend KPLS or KPLSK.

**Comment by KKDDD** [comment]
I choose  KRG , but now, KPLSK does work。Thank you!
And another situation is the predicted value will have a negative value when the actual function value approaches zero， but the sample points is Positive value。
Is that beacuse the sample points is too small to train a model (i used 100 points for  30-dimensions Rastrigin function)?
