### ISSUE TITLE
Installation fails if numpy is not yet installed

### ISSUE THREAD

**Issue by bilderbuchi** [SMTorg/smt#177]
If you install smt 0.3.4 from pypi on a clean environment, it fails because setup.py wants to use numpy, which is not available, giving a ModuleNotFoundError.

**Comment by bouhlelma** [comment]
Did you try to manually install Numpy?

**Comment by bilderbuchi** [comment]
yes, then I got farther, I think missing Cython is the next thing that tripped. In the end I managed to complete the installation. This happened in the course of installing another package actually, so I thought I'd just notify you that you have a suboptimal setup experience.

**Comment by relf** [comment]
Thanks for reporting. Indeed setup imports numpy and Cython. For Cython, it tries to install with pip if not found (but it didn't seem to work for you. I think it is not robust: if you use conda, it is better to install Cython with conda). 

Maybe a better and simpler approach would be to issue a user-friendly message: "Please install numpy" and/or "Please install Cython" if required. 

Without numpy, nothing works, but without Cython, only pure-Python surrogates work. We have to let the user know which surrogates are disabled (i.e. IDW, RBF, RTMB, RMTC).

**Comment by bilderbuchi** [comment]
> but it didn't seem to work for you

yeah I saw the try-except in setup.py. It choked on the `pip.main` call (no method `main` or something like that), but I did not dig deeper there if maybe pip API has changed or whatever. Yeah I just installed stuff with conda until the install worked :D.

I think the better approach would be to avoid unconventional imports in setup.py, and avoid/move the affected code elswehere/later, but I don't know the standard way to do things with Cython, for example.

**Comment by relf** [comment]
Those unconventional imports are required to compile extensions at setup time so... I do not know if there is an alternate option.

**Comment by bilderbuchi** [comment]
OK, no worries.

**Comment by Scherlac** [comment]
Is it possible, in case we have a local mirror without internet access, and we install smt like the command follows, we still get error about `ModuleNotFoundError: No module named 'numpy'`:

```
PIPENV_PYPI_MIRROR="https://pythonrepo.mydomain"
pipenv install "smt==0.8.0" --verbose
```

>    File "/root/.local/share/virtualenvs/test-BnvVBCnl/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
>      exec(code, locals())
>    File "<string>", line 11, in <module>
>  ModuleNotFoundError: No module named 'numpy'
>  error: subprocess-exited-with-error
>
>  × Preparing metadata (pyproject.toml) did not run successfully.
>  │ exit code: 1
>  ╰─> See above for output.

What is the source repo (index url) the setup will use to install `numpy` and `cython` during the smt package installation?

**Comment by relf** [comment]
Actually, you need to install `numpy` and `Cython` on your own, as stated above the setup depends on these libraries. See [prerequisites](https://smt.readthedocs.io/en/latest/_src_docs/getting_started.html). We should update that section because we do not even try to install `Cython` anymore.
