### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by minaskar** [SMTorg/smt#182]
Hi all, 

I'm getting the following error message when trying to install smt. Any ideas?

<pre>
(base) minas-macbook:~ minas$ pip install smt
Collecting smt
  Using cached https://files.pythonhosted.org/packages/94/32/1a45b1d6018a758455b5da7e0adc0f518cfed77d3146172550f9655c167f/smt-0.4.0.tar.gz
Requirement already satisfied: scikit-learn in ./anaconda3/lib/python3.7/site-packages (from smt) (0.22)
Requirement already satisfied: pyDOE2 in ./anaconda3/lib/python3.7/site-packages (from smt) (1.2.1)
Requirement already satisfied: matplotlib in ./anaconda3/lib/python3.7/site-packages (from smt) (3.1.2)
Requirement already satisfied: numpydoc in ./anaconda3/lib/python3.7/site-packages (from smt) (0.9.1)
Requirement already satisfied: six>=1.10 in ./anaconda3/lib/python3.7/site-packages (from smt) (1.13.0)
Requirement already satisfied: scipy in ./anaconda3/lib/python3.7/site-packages (from smt) (1.4.1)
Requirement already satisfied: joblib>=0.11 in ./anaconda3/lib/python3.7/site-packages (from scikit-learn->smt) (0.14.1)
Requirement already satisfied: numpy>=1.11.0 in ./anaconda3/lib/python3.7/site-packages (from scikit-learn->smt) (1.17.4)
Requirement already satisfied: kiwisolver>=1.0.1 in ./anaconda3/lib/python3.7/site-packages (from matplotlib->smt) (1.1.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in ./anaconda3/lib/python3.7/site-packages (from matplotlib->smt) (2.4.5)
Requirement already satisfied: python-dateutil>=2.1 in ./anaconda3/lib/python3.7/site-packages (from matplotlib->smt) (2.8.1)
Requirement already satisfied: cycler>=0.10 in ./anaconda3/lib/python3.7/site-packages (from matplotlib->smt) (0.10.0)
Requirement already satisfied: Jinja2>=2.3 in ./anaconda3/lib/python3.7/site-packages (from numpydoc->smt) (2.10.3)
Requirement already satisfied: sphinx>=1.6.5 in ./anaconda3/lib/python3.7/site-packages (from numpydoc->smt) (2.3.0)
Requirement already satisfied: setuptools in ./anaconda3/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib->smt) (42.0.2)
Requirement already satisfied: MarkupSafe>=0.23 in ./anaconda3/lib/python3.7/site-packages (from Jinja2>=2.3->numpydoc->smt) (1.1.1)
Requirement already satisfied: babel!=2.0,>=1.3 in ./anaconda3/lib/python3.7/site-packages (from sphinx>=1.6.5->numpydoc->smt) (2.7.0)
Requirement already satisfied: sphinxcontrib-serializinghtml in ./anaconda3/lib/python3.7/site-packages (from sphinx>=1.6.5->numpydoc->smt) (1.1.3)
Requirement already satisfied: alabaster<0.8,>=0.7 in ./anaconda3/lib/python3.7/site-packages (from sphinx>=1.6.5->numpydoc->smt) (0.7.12)
Requirement already satisfied: Pygments>=2.0 in ./anaconda3/lib/python3.7/site-packages (from sphinx>=1.6.5->numpydoc->smt) (2.5.2)
Requirement already satisfied: docutils>=0.12 in ./anaconda3/lib/python3.7/site-packages (from sphinx>=1.6.5->numpydoc->smt) (0.15.2)
Requirement already satisfied: sphinxcontrib-applehelp in ./anaconda3/lib/python3.7/site-packages (from sphinx>=1.6.5->numpydoc->smt) (1.0.1)
Requirement already satisfied: sphinxcontrib-devhelp in ./anaconda3/lib/python3.7/site-packages (from sphinx>=1.6.5->numpydoc->smt) (1.0.1)
Requirement already satisfied: imagesize in ./anaconda3/lib/python3.7/site-packages (from sphinx>=1.6.5->numpydoc->smt) (1.1.0)
Requirement already satisfied: requests>=2.5.0 in ./anaconda3/lib/python3.7/site-packages (from sphinx>=1.6.5->numpydoc->smt) (2.22.0)
Requirement already satisfied: packaging in ./anaconda3/lib/python3.7/site-packages (from sphinx>=1.6.5->numpydoc->smt) (19.2)
Requirement already satisfied: snowballstemmer>=1.1 in ./anaconda3/lib/python3.7/site-packages (from sphinx>=1.6.5->numpydoc->smt) (2.0.0)
Requirement already satisfied: sphinxcontrib-htmlhelp in ./anaconda3/lib/python3.7/site-packages (from sphinx>=1.6.5->numpydoc->smt) (1.0.2)
Requirement already satisfied: sphinxcontrib-qthelp in ./anaconda3/lib/python3.7/site-packages (from sphinx>=1.6.5->numpydoc->smt) (1.0.2)
Requirement already satisfied: sphinxcontrib-jsmath in ./anaconda3/lib/python3.7/site-packages (from sphinx>=1.6.5->numpydoc->smt) (1.0.1)
Requirement already satisfied: pytz>=2015.7 in ./anaconda3/lib/python3.7/site-packages (from babel!=2.0,>=1.3->sphinx>=1.6.5->numpydoc->smt) (2019.3)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./anaconda3/lib/python3.7/site-packages (from requests>=2.5.0->sphinx>=1.6.5->numpydoc->smt) (1.25.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./anaconda3/lib/python3.7/site-packages (from requests>=2.5.0->sphinx>=1.6.5->numpydoc->smt) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in ./anaconda3/lib/python3.7/site-packages (from requests>=2.5.0->sphinx>=1.6.5->numpydoc->smt) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in ./anaconda3/lib/python3.7/site-packages (from requests>=2.5.0->sphinx>=1.6.5->numpydoc->smt) (2019.11.28)
Building wheels for collected packages: smt
  Building wheel for smt (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/minas/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/02/l70vh6k13r95s3_j908sgqrw0000gp/T/pip-install-osckrkkq/smt/setup.py'"'"'; __file__='"'"'/private/var/folders/02/l70vh6k13r95s3_j908sgqrw0000gp/T/pip-install-osckrkkq/smt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/02/l70vh6k13r95s3_j908sgqrw0000gp/T/pip-wheel-wngmre_f --python-tag cp37
       cwd: /private/var/folders/02/l70vh6k13r95s3_j908sgqrw0000gp/T/pip-install-osckrkkq/smt/
  Complete output (91 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.7
  creating build/lib.macosx-10.7-x86_64-3.7/smt
  copying smt/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/smt
  creating build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
  copying smt/surrogate_models/rmts.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
  copying smt/surrogate_models/surrogate_model.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
  copying smt/surrogate_models/qp.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
  copying smt/surrogate_models/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
  copying smt/surrogate_models/ls.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
  copying smt/surrogate_models/kpls.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
  copying smt/surrogate_models/krg.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
  copying smt/surrogate_models/rbf.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
  copying smt/surrogate_models/kplsk.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
  copying smt/surrogate_models/gekpls.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
  copying smt/surrogate_models/rmtc.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
  copying smt/surrogate_models/rmtb.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
  copying smt/surrogate_models/genn.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
  copying smt/surrogate_models/krg_based.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
  copying smt/surrogate_models/idw.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
  creating build/lib.macosx-10.7-x86_64-3.7/smt/problems
  copying smt/problems/ndim_cantilever_beam.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
  copying smt/problems/robot_arm.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
  copying smt/problems/tensor_product.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
  copying smt/problems/cantilever_beam.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
  copying smt/problems/ndim_robot_arm.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
  copying smt/problems/reduced_problem.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
  copying smt/problems/water_flow.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
  copying smt/problems/lp_norm.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
  copying smt/problems/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
  copying smt/problems/ndim_rosenbrock.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
  copying smt/problems/branin.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
  copying smt/problems/welded_beam.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
  copying smt/problems/ndim_step_function.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
  copying smt/problems/problem.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
  copying smt/problems/rosenbrock.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
  copying smt/problems/wing_weight.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
  copying smt/problems/sphere.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
  copying smt/problems/torsion_vibration.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
  copying smt/problems/water_flow_lfidelity.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
  creating build/lib.macosx-10.7-x86_64-3.7/smt/sampling_methods
  copying smt/sampling_methods/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/smt/sampling_methods
  copying smt/sampling_methods/random.py -> build/lib.macosx-10.7-x86_64-3.7/smt/sampling_methods
  copying smt/sampling_methods/sampling_method.py -> build/lib.macosx-10.7-x86_64-3.7/smt/sampling_methods
  copying smt/sampling_methods/lhs.py -> build/lib.macosx-10.7-x86_64-3.7/smt/sampling_methods
  copying smt/sampling_methods/full_factorial.py -> build/lib.macosx-10.7-x86_64-3.7/smt/sampling_methods
  creating build/lib.macosx-10.7-x86_64-3.7/smt/utils
  copying smt/utils/silence.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils
  copying smt/utils/misc.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils
  copying smt/utils/sm_test_case.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils
  copying smt/utils/linear_solvers.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils
  copying smt/utils/line_search.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils
  copying smt/utils/options_dictionary.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils
  copying smt/utils/checks.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils
  copying smt/utils/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils
  copying smt/utils/caching.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils
  copying smt/utils/printer.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils
  copying smt/utils/kriging_utils.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils
  creating build/lib.macosx-10.7-x86_64-3.7/smt/utils/neural_net
  copying smt/utils/neural_net/metrics.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils/neural_net
  copying smt/utils/neural_net/fwd_prop.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils/neural_net
  copying smt/utils/neural_net/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils/neural_net
  copying smt/utils/neural_net/model.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils/neural_net
  copying smt/utils/neural_net/loss.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils/neural_net
  copying smt/utils/neural_net/activation.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils/neural_net
  copying smt/utils/neural_net/bwd_prop.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils/neural_net
  copying smt/utils/neural_net/optimizer.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils/neural_net
  copying smt/utils/neural_net/data.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils/neural_net
  creating build/lib.macosx-10.7-x86_64-3.7/smt/applications
  copying smt/applications/mfk.py -> build/lib.macosx-10.7-x86_64-3.7/smt/applications
  copying smt/applications/vfm.py -> build/lib.macosx-10.7-x86_64-3.7/smt/applications
  copying smt/applications/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/smt/applications
  copying smt/applications/application.py -> build/lib.macosx-10.7-x86_64-3.7/smt/applications
  copying smt/applications/moe.py -> build/lib.macosx-10.7-x86_64-3.7/smt/applications
  copying smt/applications/ego.py -> build/lib.macosx-10.7-x86_64-3.7/smt/applications
  running build_ext
  building 'smt.surrogate_models.rbfclib' extension
  creating build/temp.macosx-10.7-x86_64-3.7
  creating build/temp.macosx-10.7-x86_64-3.7/smt
  creating build/temp.macosx-10.7-x86_64-3.7/smt/src
  creating build/temp.macosx-10.7-x86_64-3.7/smt/src/rbf
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/minas/anaconda3/include -arch x86_64 -I/Users/minas/anaconda3/include -arch x86_64 -Ismt/src/rbf -I/Users/minas/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/Users/minas/anaconda3/include/python3.7m -c smt/src/rbf/rbfclib.cpp -o build/temp.macosx-10.7-x86_64-3.7/smt/src/rbf/rbfclib.o -std=c++11
  warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  smt/src/rbf/rbfclib.cpp:636:10: fatal error: 'ios' file not found
  #include "ios"
           ^~~~~
  1 warning and 1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for smt
  Running setup.py clean for smt
Failed to build smt
Installing collected packages: smt
    Running setup.py install for smt ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/minas/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/02/l70vh6k13r95s3_j908sgqrw0000gp/T/pip-install-osckrkkq/smt/setup.py'"'"'; __file__='"'"'/private/var/folders/02/l70vh6k13r95s3_j908sgqrw0000gp/T/pip-install-osckrkkq/smt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/02/l70vh6k13r95s3_j908sgqrw0000gp/T/pip-record-w936ox04/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/02/l70vh6k13r95s3_j908sgqrw0000gp/T/pip-install-osckrkkq/smt/
    Complete output (91 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.7
    creating build/lib.macosx-10.7-x86_64-3.7/smt
    copying smt/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/smt
    creating build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
    copying smt/surrogate_models/rmts.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
    copying smt/surrogate_models/surrogate_model.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
    copying smt/surrogate_models/qp.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
    copying smt/surrogate_models/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
    copying smt/surrogate_models/ls.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
    copying smt/surrogate_models/kpls.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
    copying smt/surrogate_models/krg.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
    copying smt/surrogate_models/rbf.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
    copying smt/surrogate_models/kplsk.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
    copying smt/surrogate_models/gekpls.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
    copying smt/surrogate_models/rmtc.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
    copying smt/surrogate_models/rmtb.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
    copying smt/surrogate_models/genn.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
    copying smt/surrogate_models/krg_based.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
    copying smt/surrogate_models/idw.py -> build/lib.macosx-10.7-x86_64-3.7/smt/surrogate_models
    creating build/lib.macosx-10.7-x86_64-3.7/smt/problems
    copying smt/problems/ndim_cantilever_beam.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
    copying smt/problems/robot_arm.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
    copying smt/problems/tensor_product.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
    copying smt/problems/cantilever_beam.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
    copying smt/problems/ndim_robot_arm.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
    copying smt/problems/reduced_problem.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
    copying smt/problems/water_flow.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
    copying smt/problems/lp_norm.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
    copying smt/problems/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
    copying smt/problems/ndim_rosenbrock.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
    copying smt/problems/branin.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
    copying smt/problems/welded_beam.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
    copying smt/problems/ndim_step_function.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
    copying smt/problems/problem.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
    copying smt/problems/rosenbrock.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
    copying smt/problems/wing_weight.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
    copying smt/problems/sphere.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
    copying smt/problems/torsion_vibration.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
    copying smt/problems/water_flow_lfidelity.py -> build/lib.macosx-10.7-x86_64-3.7/smt/problems
    creating build/lib.macosx-10.7-x86_64-3.7/smt/sampling_methods
    copying smt/sampling_methods/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/smt/sampling_methods
    copying smt/sampling_methods/random.py -> build/lib.macosx-10.7-x86_64-3.7/smt/sampling_methods
    copying smt/sampling_methods/sampling_method.py -> build/lib.macosx-10.7-x86_64-3.7/smt/sampling_methods
    copying smt/sampling_methods/lhs.py -> build/lib.macosx-10.7-x86_64-3.7/smt/sampling_methods
    copying smt/sampling_methods/full_factorial.py -> build/lib.macosx-10.7-x86_64-3.7/smt/sampling_methods
    creating build/lib.macosx-10.7-x86_64-3.7/smt/utils
    copying smt/utils/silence.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils
    copying smt/utils/misc.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils
    copying smt/utils/sm_test_case.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils
    copying smt/utils/linear_solvers.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils
    copying smt/utils/line_search.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils
    copying smt/utils/options_dictionary.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils
    copying smt/utils/checks.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils
    copying smt/utils/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils
    copying smt/utils/caching.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils
    copying smt/utils/printer.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils
    copying smt/utils/kriging_utils.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils
    creating build/lib.macosx-10.7-x86_64-3.7/smt/utils/neural_net
    copying smt/utils/neural_net/metrics.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils/neural_net
    copying smt/utils/neural_net/fwd_prop.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils/neural_net
    copying smt/utils/neural_net/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils/neural_net
    copying smt/utils/neural_net/model.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils/neural_net
    copying smt/utils/neural_net/loss.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils/neural_net
    copying smt/utils/neural_net/activation.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils/neural_net
    copying smt/utils/neural_net/bwd_prop.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils/neural_net
    copying smt/utils/neural_net/optimizer.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils/neural_net
    copying smt/utils/neural_net/data.py -> build/lib.macosx-10.7-x86_64-3.7/smt/utils/neural_net
    creating build/lib.macosx-10.7-x86_64-3.7/smt/applications
    copying smt/applications/mfk.py -> build/lib.macosx-10.7-x86_64-3.7/smt/applications
    copying smt/applications/vfm.py -> build/lib.macosx-10.7-x86_64-3.7/smt/applications
    copying smt/applications/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/smt/applications
    copying smt/applications/application.py -> build/lib.macosx-10.7-x86_64-3.7/smt/applications
    copying smt/applications/moe.py -> build/lib.macosx-10.7-x86_64-3.7/smt/applications
    copying smt/applications/ego.py -> build/lib.macosx-10.7-x86_64-3.7/smt/applications
    running build_ext
    building 'smt.surrogate_models.rbfclib' extension
    creating build/temp.macosx-10.7-x86_64-3.7
    creating build/temp.macosx-10.7-x86_64-3.7/smt
    creating build/temp.macosx-10.7-x86_64-3.7/smt/src
    creating build/temp.macosx-10.7-x86_64-3.7/smt/src/rbf
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/minas/anaconda3/include -arch x86_64 -I/Users/minas/anaconda3/include -arch x86_64 -Ismt/src/rbf -I/Users/minas/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/Users/minas/anaconda3/include/python3.7m -c smt/src/rbf/rbfclib.cpp -o build/temp.macosx-10.7-x86_64-3.7/smt/src/rbf/rbfclib.o -std=c++11
    warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    smt/src/rbf/rbfclib.cpp:636:10: fatal error: 'ios' file not found
    #include "ios"
             ^~~~~
    1 warning and 1 error generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/minas/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/02/l70vh6k13r95s3_j908sgqrw0000gp/T/pip-install-osckrkkq/smt/setup.py'"'"'; __file__='"'"'/private/var/folders/02/l70vh6k13r95s3_j908sgqrw0000gp/T/pip-install-osckrkkq/smt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/02/l70vh6k13r95s3_j908sgqrw0000gp/T/pip-record-w936ox04/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.`
</pre>

**Comment by relf** [comment]
Compilation problem on MacOSX... Maybe solution in issue #130 will help.

**Comment by minaskar** [comment]
Hi relf,

I managed to solve my issue by following your suggestion. In particular I added the following code on the top of the setup.py file and installed set from source.

```
if sys.platform == 'darwin':
    os.environ['MACOSX_DEPLOYMENT_TARGET'] = '10.9'
```

Moreover, I can confirm that one will encounter the same issue in most modern Mac machines. So it might be a good idea to include this line of code by default in the release version.

Cheers

**Comment by relf** [comment]
Actually I think you can set the environment variable then install as usual:
<pre>
$ export MACOSX_DEPLOYMENT_TARGET = '10.9'
$ pip install smt
</pre>
I can not test it, but it should do the trick.

**Comment by sudurrafuckedthworld** [comment]
hi guys i have some problem with thath shit can u help me pls?
ERROR: Command errored out with exit status 4294967295:
     command: 'c:\users\sudurra\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sudurra\\AppData\\Local\\Temp\\pip-install-zkqbpoic\\smt\\setup.py'"'"'; __file__='"'"'C:\\Users\\sudurra\\AppData\\Local\\Temp\\pip-install-zkqbpoic\\smt\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\sudurra\AppData\Local\Temp\pip-pip-egg-info-j0t7eipb'
         cwd: C:\Users\sudurra\AppData\Local\Temp\pip-install-zkqbpoic\smt\
    Complete output (1 lines):
    Numpy import failed: please install numpy module
    ----------------------------------------
ERROR: Command errored out with exit status 4294967295: python setup.py egg_info Check the logs for full command output.

**Comment by relf** [comment]
You have to install numpy. You have some guidance in the [doc](https://smt.readthedocs.io/en/latest/_src_docs/getting_started.html#getting-started)
