### ISSUE TITLE
How high is high?

### ISSUE THREAD

**Issue by minaskar** [SMTorg/smt#183]
Hi all,

This is not an issue exactly. 

The docs (and the paper) mention that unlike Kriging, KPLS(K) can deal with high-dimensional models. 

However, I find it hard to make KPLS work with anything beyond 30 dimensions (even for trivial models).

Did anyone manage to make KPLS work in such cases?

**Comment by relf** [comment]
The paper shows a problem with 60 dimensions. KPLS should allow to tackle 30-dim problems. Could you show a trivial model that did not work?

**Comment by relf** [comment]
@minaskar I close the issue for now, feel free to re-open if you have some news.
