### ISSUE TITLE
Derivatives prediction by kriging is not working

### ISSUE THREAD

**Issue by kanekosh** [SMTorg/smt#186]
## Issue
In kriging surrogates, gradient prediction provided by `predict_derivatives()` might be wrong when the option is set as `poly='linear'`.  

## Test
I took the 2D surrogate example from [GEKPLS example](https://smt.readthedocs.io/en/latest/_src_docs/surrogate_models/gekpls.html) and checked the derivative values in the following three ways. A test point at which the derivatives are computed is one of the training points, so that I can have reference values there.
1. Training derivative at a test point (reference value)
2. Predicted derivative by `sm.predict_derivatives()`
3. Finite-differenced derivative approximation of `sm.predict_values()`  

I believe 2 and 3 should always match. 1 and 2/3 may not match for digits, but at least they should give similar values.  
In my test, `KRG` and `GEKPLS` worked as expected with the default option `poly='constant'`, however, they did not when `poly='linear'`. For the latter case, 1 and 3 were consistent, while 2 (derivative prediction) gave inconsistent values. 

### Script
```python
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

from smt.surrogate_models import GEKPLS, KRG, KPLS, KPLSK
from smt.problems import Sphere
from smt.sampling_methods import LHS

def main():
    # Construction of the DOE
    fun = Sphere(ndim=2)
    sampling = LHS(xlimits=fun.xlimits, criterion="m")
    xt = sampling(20)
    yt = fun(xt)
    # Compute the training derivatives
    for i in range(2):
        yd = fun(xt, kx=i)
        yt = np.concatenate((yt, yd), axis=1)

    # check KRG models
    print('--------------------------')
    print('KRG with poly = constant' )
    sm_krg_c = KRG(theta0=[1e-2], poly='constant', print_global=False)
    sm_krg_c.set_training_values(xt, yt[:, 0])
    sm_krg_c.train()
    check_derivatives(sm_krg_c, xt, yt)

    print('--------------------------')
    print('KRG with poly = linear' )
    sm_krg_l = KRG(theta0=[1e-2], poly='linear', print_global=False)
    sm_krg_l.set_training_values(xt, yt[:, 0])
    sm_krg_l.train()
    check_derivatives(sm_krg_l, xt, yt)

    # check GEKPLS models
    print('--------------------------')
    print('GEKPLS with poly = constant' )
    sm_gekpls_c = GEKPLS(theta0=[1e-2], poly='constant', xlimits=fun.xlimits, extra_points=1, print_global=False)
    sm_gekpls_c.set_training_values(xt, yt[:, 0])
    for i in range(2):
        sm_gekpls_c.set_training_derivatives(xt, yt[:, 1 + i].reshape((yt.shape[0], 1)), i)
    sm_gekpls_c.train()
    check_derivatives(sm_gekpls_c, xt, yt)

    print('--------------------------')
    print('GEKPLS with poly = linear' )
    sm_gekpls_l = GEKPLS(theta0=[1e-2], poly='linear', xlimits=fun.xlimits, extra_points=1, print_global=False)
    sm_gekpls_l.set_training_values(xt, yt[:, 0])
    for i in range(2):
        sm_gekpls_l.set_training_derivatives(xt, yt[:, 1 + i].reshape((yt.shape[0], 1)), i)
    sm_gekpls_l.train()
    check_derivatives(sm_gekpls_l, xt, yt)

def check_derivatives(sm, xt, yt, i=10):
    # Compares three derivatives at i-th traning point
    # 1. Training derivative: "exact" value
    # 2. Predicted derivative: obtaied by sm.predict_derivatives()
    # 3. Finite-differenced derivative: forward-differencing sm.predict_values()

    # testing point
    x_test = xt[10].reshape((1,2))

    # 2. derivatives prediction by surrogate
    dydx_predict = np.zeros(2)
    dydx_predict[0] = sm.predict_derivatives(x_test, kx=0)[0,0]
    dydx_predict[1] = sm.predict_derivatives(x_test, kx=1)[0,0]

    # 3. derivative by finite-differencing sm.predict_values()
    dydx_fd = np.zeros(2)
    h = 1.e-3  # step size
    x_step1 = x_test + np.array([[h, 0.]])
    x_step2 = x_test + np.array([[0., h]])
    dydx_fd[0] = (sm.predict_values(x_step1) - sm.predict_values(x_test)) / h
    dydx_fd[1] = (sm.predict_values(x_step2) - sm.predict_values(x_test)) / h

    # compare results
    print('Test point: x=', x_test)
    print('  Training derivatives    =', yt[i, 1:])
    print('  Predicted derivatives   =', dydx_predict)
    print('  Finite-diff derivatives =', dydx_fd)
    
if __name__ == '__main__':
    main()
```
### Output
```
--------------------------
KRG with poly = constant
Test point: x= [[0.37942888 4.64215952]]
  Training derivatives    = [0.75885776 9.28431903]
  Predicted derivatives   = [0.75886037 9.28431727]
  Finite-diff derivatives = [0.75833791 9.28770331]

--------------------------
KRG with poly = linear
Test point: x= [[0.37942888 4.64215952]]
  Training derivatives    = [0.75885776 9.28431903]
  Predicted derivatives   = [3.49403164 6.46394124]
  Finite-diff derivatives = [0.76132158 9.28927155]

--------------------------
GEKPLS with poly = constant
Test point: x= [[0.37942888 4.64215952]]
  Training derivatives    = [0.75885776 9.28431903]
  Predicted derivatives   = [0.7590008 9.2832744]
  Finite-diff derivatives = [0.75934032 9.28445791]

--------------------------
GEKPLS with poly = linear
Test point: x= [[0.37942888 4.64215952]]
  Training derivatives    = [0.75885776 9.28431903]
  Predicted derivatives   = [7.29028109 8.71618885]
  Finite-diff derivatives = [0.75827747 9.28190784]
```
Notes:
- Due to the randomness in LHS, the output value above will not be reproducible. You should be able to see the discrepancy in _Predicted derivatives_ after running the script at most several times. 
- Although not included in the test script, I had the same issue with `KPLS, KPLSK`. I did not see this issue in 1D input cases. 

Thank you,
Shugo

**Comment by relf** [comment]
Thanks for this thorough report, definitely there is a problem with derivatives and linear option. I'll try to take a look...

**Comment by relf** [comment]
@kanekosh I used your script to create a new test and thanks to @sdubreui and @NatOnera the PR #188 fixes the bug.

**Comment by dimitrism1996** [comment]
Not sure if it is my fault, but i get the following error whenever i try to call predict_derivatives in the wing wight example : 
  File "/home/dimitris/SMT/smt-master/smt/surrogate_models/krg_based.py", line 348, in _predict_derivatives
    / self.X_std[kx]
IndexError: index 2 is out of bounds for axis 0 with size 2

I get the same error using every surrogate model that uses krg_based.py. The script i use is the following : 


from __future__ import print_function, division
import numpy as np
from scipy import linalg
from smt.utils import compute_rms_error

from smt.problems import  WingWeight
from smt.sampling_methods import LHS, Random
from smt.surrogate_models import LS, QP, KPLS, KRG, KPLSK, GEKPLS
try:
    from smt.surrogate_models import IDW, RBF, RMTC, RMTB
    compiled_available = True
except:
    compiled_available = False

try:
    import matplotlib.pyplot as plt
    plot_status = True
except:
    plot_status = False

import scipy.interpolate

from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
from matplotlib import cm
import pylab

########### Initialization of the problem, construction of the training and validation points

ndim = 10 #number of variables
ndoe = 50 


#Construction of the DOE for the fuction
fun = WingWeight(ndim = ndim)
sampling = LHS(xlimits = fun.xlimits, criterion = 'cm')
xt = sampling(ndoe)

#Compute the outputs
yt = fun(xt)    



# Construction of the validation points
ntest = 100
  
sampling = Random(xlimits = fun.xlimits)
xtest = sampling(ntest)
ytest = fun(xtest)



#plot of validation vs sampling points
fig = plt.figure(1)
ax = fig.add_subplot(2, 1, 1)
ax.plot(yt, yt, "o" , label = 'sampling points')
ax.plot(ytest, ytest, 'r.', label = 'validation points')

ax.set_xlabel('y')
ax.set_ylabel('y')

ax.legend(loc='upper left')
plt.title('Plot of validation vs sampling points')
#ax.set_xscale('log')
#ax.set_yscale('log')
ax.grid()
pylab.show()



#-------------------------- The KPLSK model--------------------------------#   
t = KPLSK(n_comp = 10, theta0 = [1e-2]*ndim ,print_prediction = False)
t.set_training_values(xt,yt)

t.train()


# Prediction of the validation points
y = t.predict_values(xtest)
#print('predicted values :', y)
print('KPLSK model,  err: '+ str(compute_rms_error(t,xtest,ytest)))
if plot_status:
    
# Plot the function, the prediction and the 95% confidence interval based on
# the MSE
    fig = plt.figure()
    plt.plot(ytest, ytest, '-', label='$y_{true}$')
    plt.plot(ytest, y, 'r.', label='$\hat{y}$')
   
    plt.xlabel('$y_{true}$')
    plt.ylabel('$\hat{y}$')
    
    plt.legend(loc='upper left')
    plt.title('KPLSK model: validation of the prediction model')   

if plot_status:
    plt.show()

# Value of theta
print("theta values",  t.optimal_theta)


#Computation of the gradient for the DOE points
# Compute the gradient
for i in range(ndim):
    yd = fun(xt, kx = i)

ydtest = np.zeros((ntest,ndim))   
for i in range(ndim):
    ydtest[:,i] = fun(xtest,kx = i).T


# Prediction of the derivatives with regards to each direction space
yd_prediction = np.zeros((ntest,ndim))     
for i in range(ndim):
    yd_prediction[:,i] = t.predict_derivatives(xtest, kx = i).T
    print('KPLSK model, err of the '+str(i+1)+'-th derivative: '+ str(compute_rms_error(t,xtest,ydtest[:,i],kx=i)))

    if plot_status:
        
        plt.plot(ydtest[:,i],ydtest[:,i],'-.')
        plt.plot(ydtest[:,i],yd_prediction[:,i],'.')
        plt.title('KPLSK model, prediction of the '+ str(i+1)+'-th derivate')

    if plot_status:
        plt.show()

**Comment by relf** [comment]
You're right there is still a bug here when poly is 'constant' and ndim > 2. I will push a fix.
