### ISSUE TITLE
EGO uses variance instead of standard deviation

### ISSUE THREAD

**Issue by rruusu** [SMTorg/smt#189]
Unless I am completely mistaken, the EGO application (in *smt/applications/ego.py*) uses variances (sigma squared), as returned by `KRG.predict_variances()`, where it should really use standard deviations (sigma). This affects both the EI and UCB criteria, as well as the visualization of the example in *doc/_src_docs/applications/ego.rst*.

Both the EI and UCB criteria produce better results and the error estimates and the expected improvement look much more like a Kriging model should when this is fixed by adding the necessary `np.sqrt()` calls around `predict_variances()`.

**Comment by relf** [comment]
Good catch! Thank you for the reporting and fix.
