### ISSUE TITLE
Exception: Leading minor of the array is not positive definite

### ISSUE THREAD

**Issue by VarunPai** [SMTorg/smt#208]
I tried to train a Kriging model with 2 input dimensions data read from a csv file. The code is as follows
```
#!/usr/bin/env python
# coding: utf-8
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from smt.surrogate_models import KRG

# Read CSV Data
CSVData = pd.read_csv('X1X2Y.csv')
data = CSVData.values
xt = data[:,0:2]
yt = data[:,2]

# Remove unique elements
u,indices = np.unique(xt,axis=0,return_index=True)
xt = xt[indices,:]
yt = yt[indices]

# Train the model
sm = KRG(theta0=[1e-2,1e-2])
sm.set_training_values(xt, yt)
sm.train()
```

During the training, I am getting the following error

```
_________________________________________________________________________
   
                                  Kriging
___________________________________________________________________________
   
 Problem size
   
      # training points.        : 815
   
___________________________________________________________________________
   
 Training
   
   Training ...
exception :  69-th leading minor of the array is not positive definite
exception :  79-th leading minor of the array is not positive definite
exception :  78-th leading minor of the array is not positive definite
exception :  69-th leading minor of the array is not positive definite
exception :  69-th leading minor of the array is not positive definite
exception :  79-th leading minor of the array is not positive definite
exception :  78-th leading minor of the array is not positive definite
```
What could be the reason for this error ? How can I fix this ? I am hereby attaching the code and the data I used. 

[X1X2Kriging.zip](https://github.com/SMTorg/smt/files/4868987/X1X2Kriging.zip)

**Comment by relf** [comment]
With only 3 inputs, I would say you have too many training point and this can lead to ill-conditionned kriging matrix (kriging does not like too many points too close from each other). I would suggest to try with less training points. As a rule of thumb for a small input dimension, 10*dimension training points covering your input space should work fine.

**Comment by NatOnera** [comment]
If you want to keep your 815 points in your training DOE, the other idea is to modify the correlation matrix by adding 'a small term' on the diagonal to improve the conditioning of the matrix (see this paper : https://www.asc.ohio-state.edu/statistics/comp_exp/jour.club/AndrianakisChallenor_CSDA2012.pdf).
The value of the nugget is chosen in file krg_based.py line 170; so if you modify it to :
nugget = 100.0 * MACHINE_EPSILON
instead of 
nugget = 10.0 * MACHINE_EPSILON
You won't have anymore the error.

**Comment by VarunPai** [comment]
@relf Thank you for the comment. 
As you suggested, I reduced the number of points to 30 and the training was successfull. I will keep this point in mind.

@NatOnera Thank for the suggestion and the paper link. I will try this way.
