### ISSUE TITLE
Issue while installing smt

### ISSUE THREAD

**Issue by npandey2385** [SMTorg/smt#221]
Hi ,

I am getting the following error while installing SMT. I am tried to build via source code as well as pip but same issue.

running build
running build_py
running build_ext
building 'smt.surrogate_models.rbfclib' extension
/common/pkgs/gcc/latest/bin/gcc -fgnu89-inline -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -m64 -m64 -fPIC -Ismt/src/rbf -I/common/pkgs/python/v3.7.0/lib/python3.7/site-packages/numpy/core/include -I/common/pkgs/python/v3.7.0/include/python3.7m -c smt/src/rbf/rbfclib.cpp -o build/temp.linux-x86_64-3.7/smt/src/rbf/rbfclib.o -std=c++11
cc1plus: warning: command line option '-fgnu89-inline' is valid for C/ObjC but not for C++
In file included from /common/pkgs/python/v3.7.0/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1821:0,
                 from /common/pkgs/python/v3.7.0/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /common/pkgs/python/v3.7.0/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from smt/src/rbf/rbfclib.cpp:641:
/common/pkgs/python/v3.7.0/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^~~~~~~
/common/pkgs/gcc/latest/bin/gcc -fgnu89-inline -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -m64 -m64 -fPIC -Ismt/src/rbf -I/common/pkgs/python/v3.7.0/lib/python3.7/site-packages/numpy/core/include -I/common/pkgs/python/v3.7.0/include/python3.7m -c smt/src/rbf/rbf.cpp -o build/temp.linux-x86_64-3.7/smt/src/rbf/rbf.o -std=c++11
cc1plus: warning: command line option '-fgnu89-inline' is valid for C/ObjC but not for C++
/common/pkgs/gcc/v4.8.3/bin/g++ -fgnu89-inline -pthread -shared -L/common/pkgs/tcltk/v8.6/lib -Wl,-rpath=/common/pkgs/tcltk/v8.6/lib -L/common/pkgs/python/v3.7.0/lib -Wl,-rpath=/common/pkgs/python/v3.7.0/lib -L/common/pkgs/openssl/v1.0.2h/lib -L/common/pkgs/sqlite/v3.8.8.1/lib -Wl,-rpath=/common/pkgs/openssl/v1.0.2h/lib -Wl,-rpath=/common/pkgs/sqlite/v3.8.8.1/lib -L/common/pkgs/libffi/v3.3/lib64 -L/common/pkgs/tcltk/v8.6/lib -Wl,-rpath=/common/pkgs/tcltk/v8.6/lib -L/common/pkgs/python/v3.7.0/lib -Wl,-rpath=/common/pkgs/python/v3.7.0/lib -L/common/pkgs/openssl/v1.0.2h/lib -L/common/pkgs/sqlite/v3.8.8.1/lib -Wl,-rpath=/common/pkgs/openssl/v1.0.2h/lib -Wl,-rpath=/common/pkgs/sqlite/v3.8.8.1/lib -L/common/pkgs/libffi/v3.3/lib64 build/temp.linux-x86_64-3.7/smt/src/rbf/rbfclib.o build/temp.linux-x86_64-3.7/smt/src/rbf/rbf.o -L/common/pkgs/python/v3.7.0/lib -lpython3.7m -o build/lib.linux-x86_64-3.7/smt/surrogate_models/rbfclib.cpython-37m-x86_64-linux-gnu.so
/common/pkgs/gcc/v4.8.3/bin/ld: build/temp.linux-x86_64-3.7/smt/src/rbf/rbfclib.o: unrecognized relocation (0x2a) in section `.text'
/common/pkgs/gcc/v4.8.3/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
error: command '/common/pkgs/gcc/v4.8.3/bin/g++' failed with exit status 1

**Comment by relf** [comment]
Compilation problem with the g++ build chain... What is your OS version?

**Comment by relf** [comment]
No news is good news.
