### ISSUE TITLE
EGO fails while running on Ackley

### ISSUE THREAD

**Issue by julesy89** [SMTorg/smt#244]
Thank you for your great library! I wanted to benchmark the EGO implementation on common test functions such as Ackley, Rastirigin, Himmelblau and so on and ran into the following error by running:

**Disclaimer**: I am the author of the pymoo (https://pymoo.org) framework which is used below.

```
import numpy as np
from smt.applications import EGO

from pymoo.operators.sampling.latin_hypercube_sampling import LatinHypercubeSampling
from pymoo.problems.single import Ackley

problem = Ackley()
xl, xu = problem.bounds()


def func(x):
    return problem.evaluate(x, return_values_of=["F"])


n_iter = 100
xlimits = np.column_stack([xl, xu])

xdoe = LatinHypercubeSampling().do(problem, 10).get("X")

criterion = "EI"  # 'EI' or 'SBO' or 'UCB'

ego = EGO(n_iter=n_iter, criterion=criterion, xdoe=xdoe, xlimits=xlimits)

x_opt, y_opt, _, x_data, y_data = ego.optimize(fun=func)
print(f"Minimum in x={x_opt} with f(x)={y_opt}")
```

At some point the output will be through many exepction for instance:

```
/Users/blankjul/anaconda3/envs/dev/lib/python3.7/site-packages/smt/applications/ego.py:198: RuntimeWarning: divide by zero encountered in true_divide
  args0 = (f_min - pred) / sig
exception :  86-th leading minor of the array is not positive definite
exception :  89-th leading minor of the array is not positive definite
```

I did some basic debugging of your code and the second error comes from the cholesky decomposition failing.
I suspect this is the case for the initial `theta0`. 

Is there any quick fix for that issue?

I have written a clone of the Matlab DACEFIT toolbox which is available here by the way: 
https://github.com/msu-coinlab/pydacefit

Julian

**Comment by NatOnera** [comment]
Thank you for your comment.
You can try to initialize the theta0 with different values or to change the correlation kernel (matern52 for instance). I tried both options and it seems to work now (see the code below).
Hope it could help.
Best
Nathalie
import numpy as np
from smt.applications import EGO

from pymoo.operators.sampling.latin_hypercube_sampling import LatinHypercubeSampling
from pymoo.problems.single import Ackley
from smt.surrogate_models import KRG, KPLS

problem = Ackley()
xl, xu = problem.bounds()


def func(x):
    return problem.evaluate(x, return_values_of=["F"])


n_iter = 100
xlimits = np.column_stack([xl, xu])

xdoe = LatinHypercubeSampling().do(problem, 10).get("X")

criterion = "EI"  # 'EI' or 'SBO' or 'UCB'

sm = KRG(theta0=[1.e-1]*xdoe.shape[1],print_global = False, corr='squar_exp')#corr='matern52'
ego = EGO(n_iter=n_iter, criterion=criterion, xdoe=xdoe, xlimits=xlimits, surrogate = sm)

x_opt, y_opt, _, x_data, y_data = ego.optimize(fun=func)
print('----------------------------------------')
print(f"Minimum in x={x_opt} with f(x)={y_opt}")

**Comment by relf** [comment]
@julesy89, does it work for you?
