### ISSUE TITLE
`hyper_opt` is an invalid option for KRG

### ISSUE THREAD

**Issue by k1nshuk** [SMTorg/smt#245]
Hi, as per the documentation of the Kriging surrogate, I tried to specify the option `hyper_opt` for `KRG` but encountered an assertion error
```
AssertionError: Option hyper_opt has not been declared
```
A closer look at the valid options using 
```
sm = KRG(poly='linear')
print(sm.options._declared_entries.keys())
```
showed that the valid entries are `['print_global', 'print_training', 'print_prediction', 'print_problem', 'print_solver', 'poly', 'corr', 'theta0']`. I am not sure if its an inconsistency in the documentation or a bug but I thought I'd bring to attention. Thanks!

**Comment by relf** [comment]
Hi, thank you for your reporting. This is an inconsistency of the documentation as it refers to the Github master (not the 0.6.0 release).  The <code>hyper_opt</code> option is a new kriging option in the upcoming SMT version 0.7.0.
