### ISSUE TITLE
Provide examples of passing options

### ISSUE THREAD

**Issue by microprediction** [SMTorg/smt#247]
Hello, in examples like this:
https://smt.readthedocs.io/en/latest/_src_docs/surrogate_models/idw.html
it would be good perhaps to include an example of passing in options rather than have the reader guess.

**Comment by microprediction** [comment]
I guess this works. Is it the preferred manner of setting options? 
 
        func_surrogate = IDW(p=2)
        func_surrogate.options.update({'print_global':False})

Users of other libs might expect this to be an option to __init__, no?

**Comment by relf** [comment]
Well, <code>p</code> is an option like <code>print_global</code>, so you simply have to write:
```python
func_surrogate = IDW(p=2, print_global=false)
```
