### ISSUE TITLE
cannot import name 'MGP' from 'smt.surrogate_models' 

### ISSUE THREAD

**Issue by WholeG** [SMTorg/smt#295]
the error occurs from the code of smt-mastertutorial/SMT_Tutorial.ipynb:   
from smt.surrogate_models import LS, QP, KPLS, KRG, KPLSK, GEKPLS, MGP, why the package cannot be imported?

**Comment by relf** [comment]
Which version of SMT are you using? Which Python version? Which OS? How have you installed SMT?

**Comment by relf** [comment]
No news is good news. I close.
