### ISSUE TITLE
KPLS do not work with Python 3.9 (Oct. 2020)

### ISSUE THREAD

**Issue by Paul-Saves** [SMTorg/smt#302]
Hello,
For Python 3.9, the scikit-learn version should be sklearn 0.24  https://scikit-learn.org/stable/whats_new/v0.24.html .

However, when calling the PLS of Scikit-learn 0.24 in SMT KPLS, sklearn raise the following issue: 
```
  _get_first_singular_vectors_power_method(
  File "/d/psaves/miniconda3/lib/python3.9/site-packages/sklearn/cross_decomposition/_pls.py", line 37, in _get_first_singular_vectors_power_method
    y_score = next(col for col in Y.T if np.any(np.abs(col) > eps))
 ```
Nevertheless, using scikit-learn 0.23.2 works with SMT but need to rolled back to the old Python 3.8.

**Comment by Paul-Saves** [comment]
The code that is outdated is the following in kpls.py: 

```
if version.parse(sklversion) < version.parse("0.22"):
    from sklearn.cross_decomposition.pls_ import PLSRegression as pls
else:
    from sklearn.cross_decomposition import PLSRegression as pls
    
```
And what raise error is: 

```
def _compute_pls(self, X, y):
        _pls = pls(self.options["n_comp"])
        self.coeff_pls = _pls.fit(X.copy(), y.copy()).x_rotations_  => This line 
```

**Comment by relf** [comment]
> For Python 3.9, the scikit-learn version should be sklearn 0.24

I haven't tested yet but I find rather weird that Python 3.9 requires`scikit-learn 0.24` or the other way aournd that `scikit-learn 0.24` requires Python 3.9. It seems that the `cross-decomposition` module has undergone a lot of changes with `0.24` so maybe we have to adapt our code like we did for 0.22 version.

**Comment by Paul-Saves** [comment]
To be honest, my tests were not complete. 
The real tests that I have done are the following: 
With Python 3.9 - Scikit-learn 0.23, I had problems with Mixture of Experts in SEGOMOE when creating the models. 
With Python 3.9 - Scikit-learn 0.24, I had problems with SMT but not with SEGOMOE. 

With Python 3.8 - Scikit-learn 0.23, I had problems with FAST-OAD 1.0 but not with SMT nor SEGOMOE.

**Comment by Paul-Saves** [comment]
Duplicate with #274
