### ISSUE TITLE
Importing RBF error

### ISSUE THREAD

**Issue by FanZhouwei** [SMTorg/smt#309]
When using "from smt.surrogate_models import RBF"，the codes report error. When using KRG and QP, there is no error.

**Comment by relf** [comment]
`RBF` like `IDW`, `RMTB` and `RMTC` are surrogate models written in C++. They are compiled when installing SMT using whatever compilation toolchain found on your machine. In some cases the compilation fails and the installation fails as well. In other cases the compilation succeed but the result cannot be imported (due to difference between the environment used when compiling and the one used when running python).

I guess you are in that second case, to get an error message in your python interpreter:
<pre>
(base) D:\work>python
Python 3.8.3 (default, May 19 2020, 06:50:17) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from smt.surrogate_models.rbf import RBF
>>>
</pre>

In my case there is no error message, please post the error you get and specify your environment (OS, versions, etc.).

**Comment by FanZhouwei** [comment]
Thanks for your reply.

I used the SMT tool (0.9.0) in a conda virtual environment with Python 3.7.9. The OS was Windows 10 (1909).
Messages in the interpreter are as follows:
```
(smt) C:\Users\FZW>python
Python 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from smt.surrogate_models.rbf import RBF
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Softwares\Professional\anaconda3\envs\smt\lib\site-packages\smt\surrogate_models\rbf.py", line 13, in <module>
    from smt.surrogate_models.rbfclib import PyRBF
  File "smt\src\rbf\rbfclib.pyx", line 1, in init smt.surrogate_models.rbfclib
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
>>> from smt.surrogate_models import RBF
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'RBF' from 'smt.surrogate_models' (C:\Softwares\Professional\anaconda3\envs\smt\lib\site-packages\smt\surrogate_models\__init__.py)
```

Then, I changed to a new conda virtual environment with Python 3.8.8 and installed SMT 0.9.0 using pip. It still didn't work.
The error messages are as follows:

```
(py38) C:\Users\FZW>python
Python 3.8.8 (default, Feb 24 2021, 15:54:32) [MSC v.1928 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from smt.surrogate_models.rbf import RBF
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Softwares\Professional\anaconda3\envs\py38\lib\site-packages\smt\surrogate_models\rbf.py", line 13, in <module>
    from smt.surrogate_models.rbfclib import PyRBF
  File "smt\src\rbf\rbfclib.pyx", line 1, in init smt.surrogate_models.rbfclib
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
>>> from smt.surrogate_models import RBF
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'RBF' from 'smt.surrogate_models' (C:\Softwares\Professional\anaconda3\envs\py38\lib\site-packages\smt\surrogate_models\__init__.py)
```
There was no error when importing other surrogate models like KRG.
```
>>> from smt.surrogate_models import KRG
>>>
```

**Comment by FanZhouwei** [comment]
Thanks for your reply.

I used the SMT tool (0.9.0) in a conda virtual environment with Python 3.7.9. The OS was Windows 10 (1909).
Messages in the interpreter are as follows:
```
(smt) C:\Users\FZW>python
Python 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from smt.surrogate_models.rbf import RBF
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Softwares\Professional\anaconda3\envs\smt\lib\site-packages\smt\surrogate_models\rbf.py", line 13, in <module>
    from smt.surrogate_models.rbfclib import PyRBF
  File "smt\src\rbf\rbfclib.pyx", line 1, in init smt.surrogate_models.rbfclib
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
>>> from smt.surrogate_models import RBF
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'RBF' from 'smt.surrogate_models' (C:\Softwares\Professional\anaconda3\envs\smt\lib\site-packages\smt\surrogate_models\__init__.py)
```

Then, I changed to a new conda virtual environment with Python 3.8.8 and installed SMT 0.9.0 using pip. It still didn't work.
The error messages are as follows:

```
(py38) C:\Users\FZW>python
Python 3.8.8 (default, Feb 24 2021, 15:54:32) [MSC v.1928 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from smt.surrogate_models.rbf import RBF
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Softwares\Professional\anaconda3\envs\py38\lib\site-packages\smt\surrogate_models\rbf.py", line 13, in <module>
    from smt.surrogate_models.rbfclib import PyRBF
  File "smt\src\rbf\rbfclib.pyx", line 1, in init smt.surrogate_models.rbfclib
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
>>> from smt.surrogate_models import RBF
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'RBF' from 'smt.surrogate_models' (C:\Softwares\Professional\anaconda3\envs\py38\lib\site-packages\smt\surrogate_models\__init__.py)
```
There was no error when importing other surrogate models like KRG.
```
>>> from smt.surrogate_models import KRG
>>>
```

**Comment by relf** [comment]
Which version of `numpy` are you using?

By [googling your error](https://www.google.com/search?client=firefox-b-d&q=ValueError%3A+numpy.ndarray+size+changed%2C+may+indicate+binary+incompatibility.+Expected+88+from+C+header%2C+got+80+from+PyObject), it seems related to the `numpy` version, a possible solution could be to upgrade to numpy >= 1.20 and maybe upgrade scipy as well.

**Comment by FanZhouwei** [comment]
> Which version of `numpy` are you using?
> 
> By [googling your error](https://www.google.com/search?client=firefox-b-d&q=ValueError%3A+numpy.ndarray+size+changed%2C+may+indicate+binary+incompatibility.+Expected+88+from+C+header%2C+got+80+from+PyObject), it seems related to the `numpy` version, a possible solution could be to upgrade to numpy >= 1.20 and maybe upgrade scipy as well.

Thanks for the kind advice.
I updated the NumPy from 1.19.2 to 1.20.1 and it finally worked. The problem which I met was solved.
