### ISSUE TITLE
from smt.examples.b777_engine.b777_engine import get_b777_engine, plot_b777_engine ,ModuleNotFoundError: No module named 'examle' 

### ISSUE THREAD

**Issue by WholeG** [SMTorg/smt#310]
- there is'not examples folder in the path of  \Anaconda\envs\machine_learning\Lib\site-packages\smt
- then I conda upgrade smt, the example folder still dosen't appear!
- So, I download the zip from github of smt, and copy the example folder from the smt.zip to   \Anaconda\envs\machine_learning\Lib\site-packages\smt.
- from smt.examples.b777_engine.b777_engine import get_b777_engine, plot_b777_engine  run successfully!

However, I debug the run_b777_engine_rmtb.py, it dosen't the show  the pictures !
 
**UserWarning: Matplotlib is currently using agg,  which is a non-GUI backend, so cannot show the figure.
  plt.show()**

- I modify the code  `matplotlib.use("TkAgg")` to
- `    import matplotlib
    
    matplotlib.use('TkAgg')`

But the picture is disorder.
actually, I have to modify all the codes of "agg" in every example!

maybe, it's  caused by copy the "example folder"?   thanks!!

**Comment by relf** [comment]
Indeed the examples were created when the only way to get SMT was to download the source (the `examples` directory is not packaged when installing with pip or conda). 

Examples are shown in the documentation [here](https://smt.readthedocs.io/en/latest/_src_docs/examples.html) and to generate this documentation we set a non GUI backend and save plots as images. 

I think we've added the `matplotlib.use('Agg')` at some point to avoid problems with plots as documentation is generated automatically from source in batch mode. Indeed if you just comment out this line the plots should show up.

We should update our documentation accordingly, thanks for the heads up.

**Comment by WholeG** [comment]
thanks, after I modify the code matplotlib.use('Agg') as matplotlib.use('TkAgg'), it works.
And another question: where are the explanations of the design variables of the examples . For example, what's the target, the basic meaning of the inputs of boing 777 smt.  I can't find the references.

**Comment by relf** [comment]
I don't know the source of the training data, if it is what you ask for. That said, from the code, we can derive:
* inputs: `throttle`, `altitude`, `Mach number`
* outputs: `SFC`, `thrust`

**Comment by WholeG** [comment]
thank you very much
