### ISSUE TITLE
Model for GEK in SMT.

### ISSUE THREAD

**Issue by jskgautam** [SMTorg/smt#314]
Hello,

My question is about how to use the SMT for GEK.

1. Is there any dedicated model in the SMT package for GEK. I can find models for Kriging, LS, KPLS and several others related to GEK-KPLS, etc. But I could not find model for GEK!

2. If there is no dedicated model for GEK in the SMT, then is it possible to modify something (some parameters) in the following GEKPLS model, so that it works as GEK

The model for GEKPLS (for the case- GEKPLS model using 1 PLS component and 1 approximating point) is:  

t = GEKPLS(n_comp=1, theta0=[1e-2], xlimits=fun.xlimits, delta_x=1e-2, extra_points= 1, print_prediction = False)

A very sincere thanks for your consideration to reply as soon as you can. Thank you!

Best regards,
Jay.

**Comment by relf** [comment]
If you take `n_comp=nx`, where `nx` is the dimension of the given problem input, then GEKPLS boils down to GEK.

**Comment by jskgautam** [comment]
> If you take `n_comp=nx`, where `nx` is the dimension of the given problem input, then GEKPLS boils down to GEK.

Hi relf. Thank you very much. Really really appreciate for the clarification.

**Comment by jskgautam** [comment]
Hello Relf,

I am back again, with another related question.

Lest say, the problem dimension is 4, So to use GEKPLS as GEK, i need to assign n_comp=4, as you suggested me earlier.

And so, in this case, I think, i must assign 4 values to the parameter theta0: theta0=[1e-2, 1e-2, 1e-2, 1e-2]

so, the model for GEK will look like:

t = GEKPLS(n_comp=4, theta0=[1e-2, 1e-2, 1e-2, 1e-2], xlimits=fun.xlimits, delta_x=1e-2, extra_points= 1, print_prediction = False)

I hope above adaptation for GEK for 4 dimension is correct? Thanks!

Best regards,
Jay.
