### ISSUE TITLE
Does GEKPLS work for one dimension problem? 

### ISSUE THREAD

**Issue by binjiaqm** [SMTorg/smt#316]
Here is the code.

import numpy as np
from smt.surrogate_models import GEKPLS

xt = np.linspace(0,20,10)
xt = xt.reshape(10,1)
yt = np.sin(xt)
yd = np.cos(xt)

xlimit = np.array([[0, 20]])
sm = GEKPLS(
    theta0=[1e-2], xlimits=xlimit, extra_points=1, print_prediction=False
)
sm.set_training_values(xt, yt)
sm.set_training_derivatives(xt, yd, 0)

sm.train()

I got error here. 

lib\site-packages\smt\utils\kriging_utils.py", line 1017, in ge_compute_pls
    _X[2, 1] += delta_x * (xlimits[1, 1] - xlimits[1, 0])
IndexError: index 1 is out of bounds for axis 1 with size 1

Any hints about what's going on?

**Comment by relf** [comment]
No, GEKPLS does not work for one dimension problem due to PLS requiring at least 2 dimensions.

This is a recurring question (#174, #212), we should add a note in the documentation and even better display a relevant error message stating the explanation.

**Comment by binjiaqm** [comment]
Helpful. Thank you for the clarification!

**Comment by jskgautam** [comment]
> No, GEKPLS does not work for one dimension problem due to PLS requiring at least 2 dimensions.
> 
> This is a recurring question (#174, #212), we should add a note in the documentation and even better display a relevant error message stating the explanation.

Thanks for replying this question, although, it is not my question. For several weeks, i tried to use the GEK and GEKPLS on 1 diemnional problem but i could not succeeded. Even i read the details of the literature and manuals but was not helpful to me! 

So,  I was just going to write my question here, but i found already somebody has asked this question. Now I am happy to read the answer of Mr. Relf.

thank you :)
