### ISSUE TITLE
Non-negative output constraint

### ISSUE THREAD

**Issue by Dee718** [SMTorg/smt#318]
Hey,

Is there any way to constrain any of the surrogate models in SMT to ensure the prediction output remains strictly positive (while still being able to obtain the derivatives)?  

Thanks

**Comment by relf** [comment]
Hi. There is no way to constrain a surrogate model within SMT.

**Comment by Dee718** [comment]
Ok, thanks for letting me know.

**Comment by haison19952013** [comment]
If you're confident your data is always positive, consider applying a logarithmic transformation before training. This ensures predictions remain positive. Afterward, use the exponential function to transform predictions back to their original scale. However, this approach can fail for data containing zero or near-zero values, as the log transformation results in negative infinity (-inf).
