### ISSUE TITLE
Understanding about GEKPLS model with extra_points= 0.

### ISSUE THREAD

**Issue by jskgautam** [SMTorg/smt#319]
Hello,

In SMT library, the model for GEKPLS  is given by:

t = GEKPLS(n_comp=1, theta0=[1e-2], xlimits=fun.xlimits, delta_x=1e-2, extra_points= 1, print_prediction = False)

If i set extra_points= 0 in the above model, does GEKPLS reduces to kriging?

Thank you for reading my question!

Best regards,
Jay.

**Comment by bouhlelma** [comment]
Hi,
Yes, it is basically a a standard kriging with a specific computation of the hyper-parameters coefficients

**Comment by jskgautam** [comment]
Perfect. thanks for the confirmation!
