### ISSUE TITLE
How can I use distance matrix or covariance matrix as input in `smt`

### ISSUE THREAD

**Issue by fwmeng88** [SMTorg/smt#324]
I have some data and am very interested in exploring `kriging` and `GEKPLS`, but I don't have the input `x_t`. What I can get is only a distance matrix which can be further transformed into a covariance matrix. I have the corresponding target values `y_t`. How can I use `smt` for such purposes? Many thanks in advance!

**Comment by relf** [comment]
Well... Short answer: you can't as this is not part of the public API. 

Slightly longer answer: this is open source and Python, so you can dive into the code and start [here](https://github.com/SMTorg/smt/blob/64572aa76f4713e65a4e3f79ace7e63e4fabb237/smt/surrogate_models/krg_based.py#L199) to hack the code... The indices and distances are used to get the covariance matrix [here](https://github.com/SMTorg/smt/blob/64572aa76f4713e65a4e3f79ace7e63e4fabb237/smt/surrogate_models/krg_based.py#L292). 

Good luck!

**Comment by fwmeng88** [comment]
Thank you very much for your help!! @relf
