### ISSUE TITLE
Specify hyperparameters before training 

### ISSUE THREAD

**Issue by AlexandrePlot44** [SMTorg/smt#332]
Hello, 

I would like to compute the LOO error to evaluate the performances of my Kriging Surrogate Model.

To compute LOO error, I see 2 methods :

- First one is to create N submodels using Kriging and leaving one control sample apart and alternating it each time. This method can be time consuming when N (the number of samples) is large.

- Second one is to consider that hyperparameters are the same for each submodel. In that case, I just need to create one SM with the N samples and then create all the submodels using the same hyperparameters. 
This lead me to the following question:

How can I specify the hyperparameters to the SM before training ? In other words, how to create a surrogate model without optimizing the hyperparameters ?

Thank you in advance,

Alexandre

**Comment by relf** [comment]
Hi, sorry we do not have a general API in SMT for that. 

Fortunatly, this is open source, so for Kriging you can patch the code [here](https://github.com/SMTorg/smt/blob/5a940e845a68e73d7c184263fd3f69694e866484/smt/surrogate_models/krg_based.py#L206) adding a condition on a new option let say `hyperparams_optimization` (default `True`).
It should look like:
```python
if option['hyperparams_optimization']:
    (self.best_optimal_rlf_value, self.best_optimal_par, self.best_optimal_theta) = self._optimize_hyperparam(D)
else:
    (self.best_optimal_rlf_value, self.best_optimal_par) = self._reduced_likely_hood(option[`theta0`])  
``` 
So for the first SM0 you train it as usual, for the others you set the option `hyperparams_optimization` to `False` and you set the option `theta0` to `SM0.best_optimal_theta` then you "train" them. To be tested...

**Comment by AlexandrePlot44** [comment]
Thank you for your help. I added these lines and it seems to work so far.



```python
if self.options["hyperparams_optimization"]:
    (
    self.optimal_rlf_value,
    self.optimal_par,
    self.optimal_theta,
    ) = self._optimize_hyperparam(D)
else:
    self.noise0 = np.array(self.options["noise0"])
    self.D = self._componentwise_distance(D, opt=0)
    self.optimal_theta = self.options["theta0"]
    (self.best_optimal_rlf_value, self.optimal_par) = self._reduced_likelihood_function(theta=self.options["theta0"])  

`
