### ISSUE TITLE
Installation problem : Failed building wheel for smt

### ISSUE THREAD

**Issue by nnassar98** [SMTorg/smt#336]
Hello,

I am trying to install smt on my MacBook (MacOS 12.0.1) via ´pip install smt´ but it failed (all dependencies have been separately installed to be sure). 

The terminal displayed the following screenshots : 
<img width="1105" alt="screenshot1" src="https://user-images.githubusercontent.com/26189062/142873624-69f0278d-74c0-419a-98b7-7b56eb3d8411.png">
<img width="1111" alt="screenshot2" src="https://user-images.githubusercontent.com/26189062/142873715-fb93460b-af97-4baa-b048-aa08da6a559f.png">
<img width="1114" alt="screenshot3" src="https://user-images.githubusercontent.com/26189062/142873673-8e25b701-0755-4583-931a-78722da70aeb.png">

**Comment by relf** [comment]
It seems to be related to your installation. When I google your error message, I get [this](https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a). Hope this helps.

**Comment by marina8888** [comment]
Just to say that I also originally had errors building 2 days ago, caused by the OS not being recognized (on the same day this was opened): 
I used the following commands to solve: 
`export ARCHFLAGS="-arch x86_64"` 
`CC=clang CXX=clang++ python -m pip install smt`
I'm not sure if these two issues could be related or if it's just a coincidence. If they are not, please feel free to ignore.

**Comment by relf** [comment]
Notice you can also try to use conda as [SMT is available for MacOS on conda forge](https://anaconda.org/conda-forge/smt).
I am not a MacOS user so difficult for me to help you further.

**Comment by hhyqhh** [comment]
I'm getting the same error on both macOS and Ubuntu, please help me.

**Comment by jarq6c** [comment]
> I'm getting the same error on both macOS and Ubuntu, please help me.

Note: In Ubuntu and derivatives you may need to install `python-dev` and/or `python3-dev` before installing `smt`.

**Comment by mariaelenavalencia** [comment]
Hello! 
I'm getting the same error; however, I'm in Windows. Later I tried with my Macbook and still got the same results.

**Comment by relf** [comment]
Hi @mariaelenavalencia! You should not have exactly the same error on Windows as above as it is triggered by `xcrun` which is specific to MacOS install (see the last lines). Could you copy/paste your error on Windows? How do you install smt? Maybe you could also use `conda` as mentioned above.

**Comment by mariaelenavalencia** [comment]
Hi!
I installed the library with Conda without issues, both on Windows and Mac. Thank you very much!

Just for your information, here is the error obtained by my Mac when I tried pip (sorry for the format):

![image](https://github.com/SMTorg/smt/assets/88800710/e321661a-2812-484b-9d88-c3676d641566)

Thank you again!
