### ISSUE TITLE
Are you planning to publish wheels?

### ISSUE THREAD

**Issue by alex-pradas** [SMTorg/smt#348]
Hi,
I am trying to `pip install` a python package that depends on `smt`. The installation fails since I do not have Microsoft C++ Build Tools:

```
...
building 'smt.surrogate_models.rbfclib' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for smt
```

I tried to conda `conda install` numpy, scypy, etc. but it does not work. I seem to need VS C++. Since I do not have admin rights on my machine, I cannot install it nor the packages that others have developed on top.

I was wondering if you are planning to provide wheels so we do not have to build them at the user's end.

Thanks!

**Comment by relf** [comment]
Hi. What error did you get with `conda install`? What are your Python/OS versions?

**Comment by relf** [comment]
@alex-pradas Feel free to re-open if needed.
