### ISSUE TITLE
a lot of RuntimeWarning in EGO of f(x) = xsinx

### ISSUE THREAD

**Issue by CFDerZhang** [SMTorg/smt#350]
When I tested the example the efficient global optimization (EGO) of F (x) = xsinx in documentation, although I got the same result as documentation and the result is obviously correct, I also received a lot of RuntimeWarning, such as divide by zero encountered in true_divide, invalid value encoded in multiply, which makes me very confused. For numerical calculation, divide by zero usually must be avoided, but the final result is correct in this example. Is this a bug? Will it affect the application of SMT in other calculations?

**Comment by relf** [comment]
Thanks for reporting! This seems to be a bug in LHS with ESE optimization. The warnings are issued by dead code to be removed, so without any consequences on the results.
