### ISSUE TITLE
n-dimensional problem

### ISSUE THREAD

**Issue by cjy4979** [SMTorg/smt#352]
Hi, I am struggling with a 5-dimensional problem at present.  At first I was trying to figure it out with kriging, but I failed because almost all kriging programs on github suit for problems no more than 3 dimensions. Can your tool help me solving it?

**Comment by relf** [comment]
Hi. Could you show us how you use SMT? Do you get an error?

**Comment by cjy4979** [comment]
Sorry sir, I figured it out later but forgot to update my issue.Thanks a lot for your explanation. So sorry to bother you with such a simple question. Thanks again.-------- 原始邮件 --------发件人： Rémi Lafage ***@***.***>日期： 2022年4月14日周四 晚上10:23收件人： SMTorg/smt ***@***.***>抄送： cjy4979 ***@***.***>, Author ***@***.***>主    题： Re: [SMTorg/smt] n-dimensional problem (Issue #352)
Reading your question again, I think I've misunderstood thinking you've already tried SMT. So definitely you can use SMT Kriging with 5 dimensions. You have to write something like:
xt = np.array([[x11, x12, x13, x14, x15],
               [x21, x22, x23, x24, x25],
                      ...
               [xn1, xn2, xn3, xn4, xn5]])
yt = np.array([y1, ..., yn])

sm = KRG()
sm.set_training_values(xt, yt)
sm.train()

ytest = sm.predict_values(xtest)

**Comment by relf** [comment]
Glad to hear you've succeeded.
