### ISSUE TITLE
Question on NestedLHS

### ISSUE THREAD

**Issue by Atulsingh92** [SMTorg/smt#359]
Hello, 

Is there a way that an already existing sampling set can be set into one of the HiFi set of the NestedLHS function, so that the LoFi set, is built with the nearest neighbouring capability, but on a predefined set, and not on between [0,1].

For instance, I have an experimental data (just like the one in the paper (MULTI-FIDELITY GAUSSIAN PROCESS MODEL FOR CFD AND WIND TUNNEL DATA FUSION), i.e. Reynolds, pitch and depth, as input and Nusselt as output.

And I need to define a low fidelity DOE on this existing experimental DOE.  
How could I do this using Nested LHS?

**Comment by relf** [comment]
Hi. Currently `NestedLHS` does not accept a hifi `doe` as an input but modifying the code yes you should be able to do it: replace [the first hifi DOE](https://github.com/SMTorg/smt/blob/72432cf639c32986d30d1251e945f867984882ea/smt/applications/mfk.py#L80) by your data then the nearest neighbouring processing should work as you mentionned. 

Note the current `NestedLHS` provides doe data within bounds defined in `xlimits` not just between [0, 1]
