### ISSUE TITLE
numpydoc should not be in the install_requires

### ISSUE THREAD

**Issue by psarka** [SMTorg/smt#364]
Hi,

Currently when I pip install smt, it pulls in a lot of unnecessary dependencies via numpydoc. Please consider moving numpydoc out of install_requires (I'm guessing it is only used when you build docs).

Matplotlib and packaging should also not bet there, but they are less offensive, so lower priority :)

If you are willing but short on time, I might be able to contribute a PR. Let me know.

**Comment by relf** [comment]
Hi, thanks for the heads up. 

Indeed`numpydoc`, `matplotlib` should not be in install_requires (rather in requirement.txt I suppose). It seems, it was made to make readthedocs work at the time, I have to check on that. `packaging` dependency is a leftover, after removing `scikit-learn` version checks it could be removed.
