### ISSUE TITLE
EGO function

### ISSUE THREAD

**Issue by MathewDevops** [SMTorg/smt#372]
**Hi everyone !

I discovered your librabry recently and I want to use EGO algorithm. 

So my problem is : I want to find the minimum of a function which I dont know its expression. I have a software which I a consider as a black box fonction, and it can gives me as many points I want but it's costly in terms of time. 

I see through your examples you use a function called "optimize" which generates points which are used in order to train the model.

However in this function wee need to set a parameter called "fun" and in your example "fun" is the objective function. 
In my case it's impossible to define the objective function because I don't know its expression.

So I want to know how can I use EGO in my case ?
 
Looking forward for your answer.

Best regards,**

**Comment by relf** [comment]
The API of SMT Ego is the "classic one" where you pass the objective function and the optimizer controls the calls to the function. 

What you ask for is also known as an _ask-and-tell_ API where you ask the optimizer to give you the next promising optimum location `x`, and you tell the optimizer what is the value of your function `y = f(x)` at this point, you ask again and so on. In that case you are in control of the optimization iterations. 

Maybe you can hack the current implementation doing something like:
1. Create `Ego` with the following:
   - set `xdoe` and `ydoe` to specify some initial evaluations of your function,
   - set `evaluator` with an `Evaluator` with a `run()` method which will save the suggested `x` in a file,
   - set `n_iter` to 1
2. Run `optimize` with a fake function returning a fake value
3. Retrieve the suggested `x` in the file and evaluate your function to get a new `y` 
4. Goto 1. with `xdoe = np.vstack(xdoe, x)`, `ydoe = np.vstack(ydoe, y)` 

... or just implement 'ask and tell' properly.
