### ISSUE TITLE
ego.optimize

### ISSUE THREAD

**Issue by MathewDevops** [SMTorg/smt#373]
Hello!

I tried to test ego with a criterion on the number of iterations which stop the algorithm before the maximal number of iterations.
I succeed in this part. 
So now concerning the method optimize from EGO, I call my function return by my software to calculate my new points, but the problem is that the ego.optimize recalculates at each iteration (by calling my function return by my software) every points calculated before : [xdoe + xdata].

For example, if i get 3 points in my doe and I fix my number of iteration to 5, then ego.optimize will call my function return by my software 33 times. Or if n_iter=5 and xdoe.size=3, I need to call my function 5 times (and 8 times if we consider the xdoe).

It works but it is very costly in times. So I want to know if it is possible to use ego.optimize without recalculate the points known previously?

Looking forward for your answer.

Best regards

**Comment by relf** [comment]
Hi. I am not sure to fully understand but if you specify `xdoe` **and** `ydoe`, `Ego` does not call your function on `xdoe`.

**Comment by MathewDevops** [comment]
So I integer the optimize method on my object of kind « EGO » inside a Loop.
I call my method optimize for each iteration.
So at the iteration n-i the algorithme calculates xdoe + the i points he founds.

**Comment by relf** [comment]
For each iteration, you have to create an `Ego` object with the following options:
* set `xdoe` and `ydoe`,
* set `n_iter` to 1, 
* set `evaluator` with an `Evaluator` which does not call the function but just save the given `x` 

Maybe the last point is what you missed?

**Comment by MathewDevops** [comment]
Thank's for your answer 

It's just a code problem i'll modify my script, not looping on the number of iterations but for example on the EI values.
