### ISSUE TITLE
Mistake in formulation of the Wing weight test case

### ISSUE THREAD

**Issue by m-balesdent** [SMTorg/smt#378]
Hello, 

There is a mistake in the formulation of the wing weight test case (both in the documentation and the code) : `(A / ((cos(Lambda))^2))` should be  `(A / ((cos(Lambda))^2))^0.6` according to the paper of Forrester et al. (2008) Engineering design via surrogate modeling: a practical guide, Wiley.

Regards,

Loïc and Mathieu

**Comment by Paul-Saves** [comment]
Thank you for your watchfulness . This will be patch soon, then.
