### ISSUE TITLE
[Question] Retrieving surrogate parameters

### ISSUE THREAD

**Issue by AJ1075477** [SMTorg/smt#404]
Hi, 
I've discovered SMT recently, and for optimization purposes, I was wondering if it was possible to retrieve the surrogates fitted parameters values, e.g. w_p and w_r for RBFs. 

Thanks in advance!

**Comment by relf** [comment]
Hi, 
Once trained, `w` coefficients of `rbf` surrogate are stored in `rbf.sol`.

```python
import numpy as np
from smt.surrogate_models import RBF

xt = np.array([0.0, 1.0, 2.0, 3.0, 4.0])
yt = np.array([0.0, 1.0, 1.5, 0.9, 1.0])

sm = RBF(d0=5)
sm.set_training_values(xt, yt)
sm.train()

print(f"w = {sm.sol}")
```

**Comment by AJ1075477** [comment]
Awesome, thank you very much!
