### ISSUE TITLE
Add option to use specified number for the power in the exp corr function

### ISSUE THREAD

**Issue by yqliaohk** [SMTorg/smt#408]
Hello SMT team,

I am postdoc in the MDOLab at University of Michigan. I have been using SMT for a project.
I did some work to enable using user-specified number for the exp kernel.
I am wondering if this something you would be interested in merging into the main branch.
If so, I will clean up and improve the code, and then make a PR.

Regards,
Yingqian

**Comment by NatOnera** [comment]
Dear Yingqian,
Thanks a lot for your proposal. Your contribution is welcome.
Best
Nathalie

**Comment by relf** [comment]
Fixed by #411
