### ISSUE TITLE
SMT version 1.3 or 2.0?

### ISSUE THREAD

**Issue by bonh** [SMTorg/smt#442]
I just noticed that you guys put a paper on the arxiv (congrats!) aber a new version of SMT. And that you have releases >2.0 plus the documentation lists version 2.0b. But PyPI and Conda still pull 1.3, right? I'd love to try >2.0 but is it ready for production?

**Comment by relf** [comment]
SMT 2.0 is still in beta, you can install 2.0b3 with
```
pip install --pre smt
```

**Comment by bonh** [comment]
Sounds good, thanks!
