### ISSUE TITLE
Can't Run Example EGO Code

### ISSUE THREAD

**Issue by JamesDean64** [SMTorg/smt#449]
I am working on an optimization project for school and wanted to use EGO because of the long run times of the analysis jobs. I am attempting to run the example code for EGO now and running into an issue. I copy and pasted the code under the usage section from here: https://github.com/SMTorg/smt/blob/master/doc/_src_docs/applications/ego.rst
I get the error message "Option design_space has not been declared". I'm not sure what this means. I've been looking into the error a bit and it doesn't make sense because the example code passes a design_space variable into the KRG function which is where the error occurs. I don't understand why it is saying design_space isn't declared when it's defined above. 

Is there some setup step that I was missing or is there code that needs to be added to set this up? I would really appreciate any advice on this. Thank you!

**Comment by relf** [comment]
I guess you have installed SMT 1.3 (the SMT **stable** version) and you are trying to run the EGO example from the **latest** doc of the upcoming SMT 2.0 (not released yet). Try running the EGO example from the [stable version doc](https://smt.readthedocs.io/en/stable/_src_docs/applications/ego.html).

**Comment by JamesDean64** [comment]
That is working for me! Thank you so much. When I do "pip show smt", it says version "smt-1.3.0" so you were 100% correct. Thank you!
