### ISSUE TITLE
Kriging surrogate model in case of multiple outputs

### ISSUE THREAD

**Issue by Ayubirad** [SMTorg/smt#455]
Hi guys,

I just created a kriging model for a function with multiple outputs using SMT tutorial. But the model is a "List". How can I use such a model for optimization, etc.?

Best regards,
Mohammad

**Comment by Paul-Saves** [comment]
https://github.com/SMTorg/smt/blob/master/tutorial/SMT_EGO_application.ipynb

**Comment by Ayubirad** [comment]
> https://github.com/SMTorg/smt/blob/master/tutorial/SMT_EGO_application.ipynb https://colab.research.google.com/github/SMTorg/smt/blob/master/tutorial/SMT_EGO_application.ipynb

Thanks, but I don't see anything concerning the minimization of a multiple output function. Suppose I want to use PSO to minimize the kriging surrogate model, how can I implement this?

**Comment by NatOnera** [comment]
Be careful when you have multiple outputs, Gaussian Process in SMT does not consider correlation between outputs, a independant GP is built for each of the output. You could do save the GP as you want (a list of model or a different name for each) for your PSO optimization.

**Comment by Ayubirad** [comment]
Dear @NatOnera 
If I understand correctly, in my case, I should build 14 kriging surrogate models, and use each predicted output to build the objective function for optimization, correct?

**Comment by NatOnera** [comment]
Exactly
