### ISSUE TITLE
Any interest in putting this on conda-forge?

### ISSUE THREAD

**Issue by timothyas** [SMTorg/smt#482]
First I want to say thanks for a great package! My colleagues and I have gotten great use out of it. We are making our own software package that we would like to make available on [conda-forge](https://conda-forge.org/docs/) so it can easily be installed via conda. However, all dependencies have to be packaged by conda-forge as well. smt is the only dependency that we have that is not on conda-forge, so I'm curious if this is of any interest in doing this, and/or if you have the time.

Thanks again!

**Comment by relf** [comment]
Happy to hear you find SMT useful. Regarding your request [SMT is already available on conda-forge](https://anaconda.org/conda-forge/smt). Only there was a packaging problem with SMT 2.1 and 2.2 releases, but I've just fixed it with the 2.2.1 release, so...

**Comment by timothyas** [comment]
Thank you @relf! I was able to install smt 2.2.1 via conda forge so I'm all set.
