### ISSUE TITLE
Adaptive sampling methods for Kriging models and its variants including multi-fidelity Kriging

### ISSUE THREAD

**Issue by haison19952013** [SMTorg/smt#494]
- I'm currently exploring different adaptive sampling methods for building efficient Kriging models and their variants, including multi-fidelity Kriging. While I have a basic understanding of some techniques like Expected Improvement (EI) and Upper Confidence Bound (UCB), I'd love to hear your thoughts and recommendations on other promising approaches.

- Specifically, I'm interested in:

1. Recommendations for different adaptive sampling methods: What are some effective methods beyond EI and UCB, especially for tackling multi-fidelity Kriging?

2. Comparison of different methods: How do different methods compare in terms of performance, efficiency, and ease of implementation?

3. Applications and limitations: In what specific situations are certain methods more suitable? Are there any known limitations or drawbacks to consider?

4. Resources and code libraries: Are there any valuable resources, tutorials, or code libraries available to help implement and compare different adaptive sampling methods for Kriging?

- Any insights, experiences, or suggestions you can offer would be greatly appreciated. I'm eager to learn from your expertise and collaborate to further explore this fascinating field of adaptive Kriging.

Thank you for your time and consideration!

**Comment by relf** [comment]
Hi thank you for your interest but you ask very very broad questions which are not directly related to SMT implementation and go far beyond the scope of SMT issues. So I am sorry but I am closing this.
