### ISSUE TITLE
AttributeError: 'DesignSpace' object has no attribute '_cs'

### ISSUE THREAD

**Issue by nrthlxne** [SMTorg/smt#498]
I tried to to import a model from a pickle file and encountered the error in the title when trying to run `sm.predict_values()`, where `sm` is the name of the imported model. According to the traceback the error originates from the `design_space.py` file, line 891 `if selt._cs is not None:`. This error only shows up in the recent version 2.2.1 (downloaded and installed yesterday) and is encountered on Windows, as well as Linux. I tested an older version (2.0.1) on a different machine and no error was returned.

When adding `self._cs = None` at the line above the if-statement, no error is returned and I obtain the expected results. It looks like `self._cs` is not properly initialized for some reason. This is only encountered when trying to use `predict_values()`, while `predict_derivatives()` works fine.

**Comment by relf** [comment]
The following code works for me:
```python
import numpy as np
import matplotlib.pyplot as plt

from smt.surrogate_models import KRG
from smt.applications.mixed_integer import MixedIntegerKrigingModel
from smt.utils.design_space import DesignSpace, IntegerVariable

import pickle

xt = np.array([0.0, 2.0, 3.0])
yt = np.array([0.0, 1.5, 0.9])

design_space = DesignSpace(
    [
        IntegerVariable(0, 4),
    ]
)
sm = MixedIntegerKrigingModel(
    surrogate=KRG(design_space=design_space, theta0=[1e-2])
)
sm.set_training_values(xt, yt)
sm.train()

num = 500
x = np.linspace(0.0, 4.0, num)
y = sm.predict_values(x)
# estimated variance
s2 = sm.predict_variances(x)

filename = "kriging.pkl"
with open(filename, "wb") as f:
   pickle.dump(sm, f)

sm2 = None
filename = "kriging.pkl"
with open(filename, "rb") as f:
   sm2 = pickle.load(f)

y_2 = sm2.predict_values(x)
# estimated variance
s2_2 = sm2.predict_variances(x)

np.testing.assert_almost_equal(y, y_2)
np.testing.assert_almost_equal(s2, s2_2)
```
Could you try it? (Please copy/paste the error message if any)
I guess you may have saved and loaded with different SMT installation.

**Comment by nrthlxne** [comment]
Thank you for the fast response, I will give your code a try and report back later today. 

You are right, the model was generated and saved using version 2.1.0. There was no issue loading and using the model with version 2.0.1 and the above described error was returned when using version 2.2.1.

**Comment by relf** [comment]
The `self._cs` attribute was introduced in #474 in SMT 2.2, it makes a model pickled with previous versions incompatible (sorry for that!). So I guess either you generate your model again with SMT 2.2+ or you just keep SMT 2.1 or... you patch like you did.

**Comment by relf** [comment]
Closing. Hope you found your way.
