### ISSUE TITLE
ValueError by passing an int instead of a float

### ISSUE THREAD

**Issue by mdelozzo** [SMTorg/smt#528]
Hi,

I got a `ValueError` when evaluating a `SurrogateModel` with an integer (`long`) instead of a float (`double`):

```
ValueError: Buffer dtype mismatch, expected 'double' but got 'long'
```

Here is the reproducer:

```python
from numpy import array
from numpy import linspace
from smt.surrogate_models import RBF

input_data = linspace(-1, 1, 10)
output_data = input_data**2

smt_model = RBF()
smt_model.set_training_values(input_data, output_data)
smt_model.train()

smt_model.predict_values(array([1])) # KO
# smt_model.predict_values(array([1.0]))  # OK
```

Is this normal or a bug? If it's normal, what's the explanation for this?

Thank you in advance for your reply,

Best,

Matthias

**Comment by relf** [comment]
Hi Matthias. I would say it is normal. Historically, SMT only handles numpy arrays of floats.

**Comment by mdelozzo** [comment]
Hi Rémi, 
Thanks for your quick reply. 
The error message surprised me a little and the notion of _buffer_ was not obvious (I was expecting to read _input value_ or something like that). I'm creating a wrapper of `SurrogateModel` and I think I will force the conversion to float to avoid any problems.
As it is the expected SMT behavior, I close this issue.

**Comment by relf** [comment]
FYI, actually RBF is written in C++ and cythonized which explains the "weird" error message.
