### ISSUE TITLE
Meta: add "Discussions" to GitHub repo?

### ISSUE THREAD

**Issue by GregVernon** [SMTorg/smt#549]
I didn't see any forum or other community location for discussion / general Q&A for SMT listed on the project website.  Various other open-source projects have enabled [GitHub Discussions](https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/about-discussions) for their GitHub-based repositories and I thought maybe SMT might consider doing so too.

Examples:
* MOOSE: https://github.com/idaholab/moose/discussions
* Dakota: https://github.com/orgs/snl-dakota/discussions
* Firedrake: https://github.com/firedrakeproject/firedrake/discussions

**Comment by relf** [comment]
Ok, it's enabled now.
