### ISSUE TITLE
Number of parameters can be handled by KPLSK

### ISSUE THREAD

**Issue by Val4on** [SMTorg/smt#565]
Hi, how many parameters can be handled by KPLSK? I have a test case which has 100 parameters, but it's asking for 4096 points to build a model, how can I reduce number of points required for DOE?

**Comment by relf** [comment]
Hi, I am not sure to understand... Your training input data is an array of shape (4096, 100) ? Do you have an error by applying KPLSK ?

**Comment by NatOnera** [comment]
Hi, I tried to train KPLSK with a DOE (500, 100) and everything seams fine. Here is the few lines of code. Only the training time is quite long. 

import numpy as np

from smt.surrogate_models import KPLSK
from smt.sampling_methods import LHS
from smt.problems import LpNorm

dim = 100
problem = LpNorm(ndim=dim)

xlimits = problem.xlimits
sampling = LHS(xlimits=xlimits)

num = 500
xt = sampling(num)
yt=problem(xt)

sm = KPLSK(theta0=[1e-2])
sm.set_training_values(xt, yt)
sm.train()
print('training done')
#to have test data
num=1000
xtest = sampling(num)
ytest=problem(xtest)
ypred=sm.predict_values(xtest)
plt.plot(ytest, ypred , "o")

**Comment by NatOnera** [comment]
To reduce training time, a possibility is to use GPX (with or without dimension reduction )
sm = GPX(theta0=[1e-2])
sm = GPX(theta0=[1e-2], kpls_dim=50)
