### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by NAThompson** [SMTorg/smt#566]
While using this library, I get the following warning:

```
~/lib/python3.12/site-packages/smt/utils/linear_solvers.py:304: DeprecationWarning: 'scipy.sparse.linalg.cg' keyword argument `tol` is deprecated in favor of `rtol` and will be removed in SciPy v1.14.0. Until then, if set, it will override `rtol`.
    tmp, _ = self.solver(
```

Looks like the offending line is

https://github.com/SMTorg/smt/blob/f8fe3450fd1fc3c069e160773089aa0a7ca89771/smt/utils/linear_solvers.py#L267

and that this could actually lead to breakages.

**Comment by relf** [comment]
Seems we will have a problem when scipy 1.14 is out. Thanks for the heads up!
