### ISSUE TITLE
Document mapping between function arguments and equations

### ISSUE THREAD

**Issue by NAThompson** [SMTorg/smt#569]
In the [documentation for RMTS](https://smt.readthedocs.io/en/latest/_src_docs/surrogate_models/rmts.html), we see the equation

$$
\min_{w}  \frac{1}{2} \mathbf{w}^{T}\mathbf{H}\mathbf{w} +  \frac{1}{2}\beta \mathbf{w}^{T}\mathbf{w} + \frac{1}{2}\frac{1}{\alpha} \sum_{i}^{nt} [F(x_i) -  y_{t_i}]^2
$$

where "α and β are regularization coefficients".  In the usage section, we see the example code

```python
sm = RMTC(
    xlimits=xlimits,
    num_elements=20,
    energy_weight=1e-15,
    regularization_weight=0.0,
)
```

It would appear that `energy_weight` is β, and that the regularization weight is 1/α? Nonetheless, this relation is not made explicit. Would it be sensible to update the docs thusly?

```python
sm = RMTC(
    xlimits=xlimits,
    num_elements=20,
    energy_weight=1e-15, # corresponds to β in  equation (1)
    regularization_weight=0.0, # corresponds to α in equation (1)
)
```

**Comment by relf** [comment]
I agree the mapping between the documentation and the API is not clear. 
Actually, we should mention explicitely in the documentation the section _3.5 - Summary and implementation_ of the paper. It defines α'=α and β'=αβ which corresponds respectively to the `energy_weight` and the `regularization_weight` arguments (so the opposite of what is stated above).
