### ISSUE TITLE
KeyError: 'C'

### ISSUE THREAD

**Issue by ilaudo** [SMTorg/smt#599]
Hello, I just recently updated to the current version of SMT in my Spyder environment, and now each time I try to train my Kriging model using the following line of code:
`test_kriging = KRG(theta0=[1e-6], print_global=False)`
I recevie the following error:
`KeyError: 'C'`

I have never received this error before, and tried training my model on data I know has worked before; however, I continually receive this error. Am I missing something obvious here, or is this an issue of the code?
As well, I noticed that before updating, `theta0` could be set to much smaller values than `1e-6`--was this another new change within the update? Thanks!

**Comment by relf** [comment]
Hi, could you provide the full error message (traceback showing where the error is raised)? You can also just copy [this example](https://smt.readthedocs.io/en/latest/_src_docs/surrogate_models/gpr/krg.html#example-1) in a test_krg.py file and run it to see if you get the same error.

For the second points, theta bounds are intended to be controlled by `theta_bounds` option (default is [1e-6, 20]). Sorry, you may be the collateral victim of a bug fix (maybe in #544). Just set `theta_bounds` option as desired.

**Comment by relf** [comment]
superseded by #601
