### ISSUE TITLE
Documentation hyperlink failing

### ISSUE THREAD

**Issue by NicolasJeanGonel** [SMTorg/smt#612]
The link in the documentation [Handling of Mixed Integer variables](https://github.com/SMTorg/smt/blob/master/tutorial/SMT_MixedInteger_application.ipynb), should return a notebook but is giving a 404 error.
 It can be found [here](https://smt.readthedocs.io/en/latest/_src_docs/getting_started.html). It is entitled "Handling of mixed integer variables".

**Comment by relf** [comment]
fixed by  #617
