### ISSUE TITLE
Bug with plt.show() and smt

### ISSUE THREAD

**Issue by Baraton-L** [SMTorg/smt#687]
Hello,
I have an issue with the function plt.show() and smt that I don't understand. Running the attached code with or without the line importing the module MixedIntegerKrigingModel does not provide the same output.
It seems that smt prevents displaying the figure that plt.show() tries to plot.
Thank you for your help !

[bug_pltshow_smt.zip](https://github.com/user-attachments/files/18010772/bug_pltshow_smt.zip)

**Comment by relf** [comment]
To be confirmed, but I think this issue is fixed by #678. Can you test your code against smt master?

**Comment by Paul-Saves** [comment]
I agree with @relf that the bug has been addressed already and fixed in #678 .

**Comment by relf** [comment]
Fixed by  #678
